

-- Update the handle_new_user function to include username if it exists (Optional, depending on if you use triggers)
-- This is an example of how you might update the trigger if you are using one:
-- CREATE OR REPLACE FUNCTION public.handle_new_user()
-- RETURNS trigger
-- LANGUAGE plpgsql
-- SECURITY DEFINER SET search_path = public
-- AS $$
-- BEGIN
--   INSERT INTO public.users (id, email, full_name, avatar_url, username)
--   VALUES (
--     new.id, 
--     new.email, 
--     new.raw_user_meta_data->>'full_name', 
--     new.raw_user_meta_data->>'avatar_url',
--     new.raw_user_meta_data->>'username'
--   );
--   RETURN new;
-- END;
-- $$;
