///
/// Generated file. Do not edit.
///
// coverage:ignore-file
// ignore_for_file: type=lint, unused_import
// dart format off

import 'package:flutter/widgets.dart';
import 'package:intl/intl.dart';
import 'package:slang/generated.dart';
import 'package:slang/overrides.dart';
import 'resources.g.dart';

// Path: <root>
class TranslationsTr with BaseTranslations<AppLocale, Translations> implements Translations {
	/// You can call this constructor and build your own translation instance of this locale.
	/// Constructing via the enum [AppLocale.build] is preferred.
	/// [AppLocaleUtils.buildWithOverrides] is recommended for overriding.
	TranslationsTr({Map<String, Node>? overrides, PluralResolver? cardinalResolver, PluralResolver? ordinalResolver, TranslationMetadata<AppLocale, Translations>? meta})
		: $meta = meta ?? TranslationMetadata(
		    locale: AppLocale.tr,
		    overrides: overrides ?? {},
		    cardinalResolver: cardinalResolver,
		    ordinalResolver: ordinalResolver,
		  ) {
		$meta.setFlatMapFunction(_flatMapFunction);
	}

	/// Metadata for the translations of <tr>.
	@override final TranslationMetadata<AppLocale, Translations> $meta;

	/// Access flat map
	@override dynamic operator[](String key) => $meta.getTranslation(key);

	late final TranslationsTr _root = this; // ignore: unused_field

	@override 
	TranslationsTr $copyWith({TranslationMetadata<AppLocale, Translations>? meta}) => TranslationsTr(meta: meta ?? this.$meta);

	// Translations
	@override String get localLanguageCode => TranslationOverrides.string(_root.$meta, 'localLanguageCode', {}) ?? 'tr_TR';
	@override String get home => TranslationOverrides.string(_root.$meta, 'home', {}) ?? 'Anasayfa';
	@override String get categories => TranslationOverrides.string(_root.$meta, 'categories', {}) ?? 'Kategoriler';
	@override String get cart => TranslationOverrides.string(_root.$meta, 'cart', {}) ?? 'Sepetim';
	@override String get favorites => TranslationOverrides.string(_root.$meta, 'favorites', {}) ?? 'Favorilerim';
	@override String get profile => TranslationOverrides.string(_root.$meta, 'profile', {}) ?? 'Profil';
	@override String get myProfile => TranslationOverrides.string(_root.$meta, 'myProfile', {}) ?? 'Profilim';
	@override String get settings => TranslationOverrides.string(_root.$meta, 'settings', {}) ?? 'Ayarlar';
	@override String get search => TranslationOverrides.string(_root.$meta, 'search', {}) ?? 'Ara';
	@override String get apply => TranslationOverrides.string(_root.$meta, 'apply', {}) ?? 'Uygula';
	@override String get clear => TranslationOverrides.string(_root.$meta, 'clear', {}) ?? 'Temizle';
	@override String get save => TranslationOverrides.string(_root.$meta, 'save', {}) ?? 'Kaydet';
	@override String get cancel => TranslationOverrides.string(_root.$meta, 'cancel', {}) ?? 'İptal';
	@override String get myInformation => TranslationOverrides.string(_root.$meta, 'myInformation', {}) ?? 'Bilgilerim';
	@override String get myAddresses => TranslationOverrides.string(_root.$meta, 'myAddresses', {}) ?? 'Adreslerim';
	@override String get changePassword => TranslationOverrides.string(_root.$meta, 'changePassword', {}) ?? 'Şifre Değiştir';
	@override String get myOrders => TranslationOverrides.string(_root.$meta, 'myOrders', {}) ?? 'Siparişlerim';
	@override String get myReviews => TranslationOverrides.string(_root.$meta, 'myReviews', {}) ?? 'Değerlendirmelerim';
	@override String get logout => TranslationOverrides.string(_root.$meta, 'logout', {}) ?? 'Çıkış Yap';
	@override String get login => TranslationOverrides.string(_root.$meta, 'login', {}) ?? 'Giriş Yap';
	@override String get signup => TranslationOverrides.string(_root.$meta, 'signup', {}) ?? 'Kayıt Ol';
	@override String get country => TranslationOverrides.string(_root.$meta, 'country', {}) ?? 'Ülke';
	@override String get city => TranslationOverrides.string(_root.$meta, 'city', {}) ?? 'Şehir';
	@override String get address => TranslationOverrides.string(_root.$meta, 'address', {}) ?? 'Adres';
	@override String get postalCode => TranslationOverrides.string(_root.$meta, 'postalCode', {}) ?? 'Posta Kodu';
	@override String get phoneNumber => TranslationOverrides.string(_root.$meta, 'phoneNumber', {}) ?? 'Telefon Numarası';
	@override String get selectCountry => TranslationOverrides.string(_root.$meta, 'selectCountry', {}) ?? 'Ülke Seçiniz';
	@override String get appTitle => TranslationOverrides.string(_root.$meta, 'appTitle', {}) ?? 'Mağaza Supabase';
	@override String get noProducts => TranslationOverrides.string(_root.$meta, 'noProducts', {}) ?? 'Ürün bulunamadı.';
	@override String get sort => TranslationOverrides.string(_root.$meta, 'sort', {}) ?? 'Sırala';
	@override String get filter => TranslationOverrides.string(_root.$meta, 'filter', {}) ?? 'Filtrele';
	@override String get languageChanged => TranslationOverrides.string(_root.$meta, 'languageChanged', {}) ?? 'Dil Türkçe olarak değiştirildi';
	@override String get addressUpdated => TranslationOverrides.string(_root.$meta, 'addressUpdated', {}) ?? 'Adres başarıyla güncellendi!';
	@override String get adminDashboard => TranslationOverrides.string(_root.$meta, 'adminDashboard', {}) ?? 'Yönetici Paneli';
	@override String get users => TranslationOverrides.string(_root.$meta, 'users', {}) ?? 'Kullanıcılar';
	@override String get products => TranslationOverrides.string(_root.$meta, 'products', {}) ?? 'Ürünler';
	@override String get orders => TranslationOverrides.string(_root.$meta, 'orders', {}) ?? 'Siparişler';
	@override String get language => TranslationOverrides.string(_root.$meta, 'language', {}) ?? 'Dil';
	@override String get noCategories => TranslationOverrides.string(_root.$meta, 'noCategories', {}) ?? 'Kategori bulunamadı.';
	@override String get emptyCart => TranslationOverrides.string(_root.$meta, 'emptyCart', {}) ?? 'Sepetiniz boş.';
	@override String get total => TranslationOverrides.string(_root.$meta, 'total', {}) ?? 'Toplam';
	@override String get proceedToCheckout => TranslationOverrides.string(_root.$meta, 'proceedToCheckout', {}) ?? 'Ödemeye Geç';
	@override String get remove => TranslationOverrides.string(_root.$meta, 'remove', {}) ?? 'Kaldır';
	@override String get loginSignup => TranslationOverrides.string(_root.$meta, 'loginSignup', {}) ?? 'Giriş Yap / Kayıt Ol';
	@override String get noFavorites => TranslationOverrides.string(_root.$meta, 'noFavorites', {}) ?? 'Henüz favori ürününüz yok.';
	@override String get helpSupport => TranslationOverrides.string(_root.$meta, 'helpSupport', {}) ?? 'Yardım & Destek';
	@override String get searchProducts => TranslationOverrides.string(_root.$meta, 'searchProducts', {}) ?? 'Ürün Ara';
	@override String get noResultsFor => TranslationOverrides.string(_root.$meta, 'noResultsFor', {}) ?? 'Sonuç bulunamadı:';
	@override String get startTyping => TranslationOverrides.string(_root.$meta, 'startTyping', {}) ?? 'Aramak için yazmaya başlayın...';
	@override String get darkMode => TranslationOverrides.string(_root.$meta, 'darkMode', {}) ?? 'Karanlık Mod';
	@override String get addToCart => TranslationOverrides.string(_root.$meta, 'addToCart', {}) ?? 'Sepete Ekle';
	@override String get reviews => TranslationOverrides.string(_root.$meta, 'reviews', {}) ?? 'Yorumlar';
	@override String get writeReview => TranslationOverrides.string(_root.$meta, 'writeReview', {}) ?? 'Yorum Yaz';
	@override String get rating => TranslationOverrides.string(_root.$meta, 'rating', {}) ?? 'Puan';
	@override String get reviewTitle => TranslationOverrides.string(_root.$meta, 'reviewTitle', {}) ?? 'Yorum Başlığı';
	@override String get yourReview => TranslationOverrides.string(_root.$meta, 'yourReview', {}) ?? 'Yorumunuz';
	@override String get submitReview => TranslationOverrides.string(_root.$meta, 'submitReview', {}) ?? 'Yorumu Gönder';
	@override String get username => TranslationOverrides.string(_root.$meta, 'username', {}) ?? 'Kullanıcı Adı';
	@override String get email => TranslationOverrides.string(_root.$meta, 'email', {}) ?? 'E-posta';
	@override String get dateOfBirth => TranslationOverrides.string(_root.$meta, 'dateOfBirth', {}) ?? 'Doğum Tarihi';
	@override String get selectGender => TranslationOverrides.string(_root.$meta, 'selectGender', {}) ?? 'Cinsiyet Seçin';
	@override String get savePersonalInfo => TranslationOverrides.string(_root.$meta, 'savePersonalInfo', {}) ?? 'Kişisel Bilgileri Kaydet';
	@override String get profileUpdated => TranslationOverrides.string(_root.$meta, 'profileUpdated', {}) ?? 'Profil başarıyla güncellendi!';
	@override String get saveAddress => TranslationOverrides.string(_root.$meta, 'saveAddress', {}) ?? 'Adresi Kaydet';
	@override String get newPassword => TranslationOverrides.string(_root.$meta, 'newPassword', {}) ?? 'Yeni Şifre';
	@override String get confirmNewPassword => TranslationOverrides.string(_root.$meta, 'confirmNewPassword', {}) ?? 'Yeni Şifreyi Onayla';
	@override String get updatePassword => TranslationOverrides.string(_root.$meta, 'updatePassword', {}) ?? 'Şifreyi Güncelle';
	@override String get passwordChanged => TranslationOverrides.string(_root.$meta, 'passwordChanged', {}) ?? 'Şifre başarıyla değiştirildi!';
	@override String get productAddedToCart => TranslationOverrides.string(_root.$meta, 'productAddedToCart', {}) ?? 'Ürün sepete eklendi!';
	@override String get failedToAddCart => TranslationOverrides.string(_root.$meta, 'failedToAddCart', {}) ?? 'Ürün eklenemedi. Lütfen giriş yapıp tekrar deneyin.';
	@override String get reviewSubmitted => TranslationOverrides.string(_root.$meta, 'reviewSubmitted', {}) ?? 'Yorum gönderildi!';
	@override String get failedSubmitReview => TranslationOverrides.string(_root.$meta, 'failedSubmitReview', {}) ?? 'Yorum gönderilemedi. Giriş yaptığınızdan ve yorumun boş olmadığından emin olun.';
	@override String get account => TranslationOverrides.string(_root.$meta, 'account', {}) ?? 'Hesap';
	@override String get shopping => TranslationOverrides.string(_root.$meta, 'shopping', {}) ?? 'Alışveriş';
	@override String get general => TranslationOverrides.string(_root.$meta, 'general', {}) ?? 'Genel';
	@override String get admin => TranslationOverrides.string(_root.$meta, 'admin', {}) ?? 'Yönetici';
	@override String get coupons => TranslationOverrides.string(_root.$meta, 'coupons', {}) ?? 'Kuponlar';
	@override String get welcomeTitle => TranslationOverrides.string(_root.$meta, 'welcomeTitle', {}) ?? 'Mağazaya Hoşgeldiniz';
	@override String get welcomeSubtitle => TranslationOverrides.string(_root.$meta, 'welcomeSubtitle', {}) ?? 'Devam etmek için giriş yapın veya hesap oluşturun';
	@override String get dontHaveAccount => TranslationOverrides.string(_root.$meta, 'dontHaveAccount', {}) ?? 'Hesabınız yok mu? Kayıt Ol';
	@override String get alreadyHaveAccount => TranslationOverrides.string(_root.$meta, 'alreadyHaveAccount', {}) ?? 'Zaten hesabınız var mı? Giriş Yap';
	@override String get signIn => TranslationOverrides.string(_root.$meta, 'signIn', {}) ?? 'Giriş Yap';
	@override String get totalRevenue => TranslationOverrides.string(_root.$meta, 'totalRevenue', {}) ?? 'Toplam Gelir';
	@override String get totalOrders => TranslationOverrides.string(_root.$meta, 'totalOrders', {}) ?? 'Toplam Sipariş';
	@override String get totalUsers => TranslationOverrides.string(_root.$meta, 'totalUsers', {}) ?? 'Toplam Kullanıcı';
	@override String get totalProducts => TranslationOverrides.string(_root.$meta, 'totalProducts', {}) ?? 'Toplam Ürün';
	@override String get recentOrders => TranslationOverrides.string(_root.$meta, 'recentOrders', {}) ?? 'Son Siparişler';
	@override String get noRecentOrders => TranslationOverrides.string(_root.$meta, 'noRecentOrders', {}) ?? 'Son sipariş yok.';
	@override String get orderNumber => TranslationOverrides.string(_root.$meta, 'orderNumber', {}) ?? 'Sipariş #';
	@override String get guest => TranslationOverrides.string(_root.$meta, 'guest', {}) ?? 'Misafir';
	@override String get newUsers => TranslationOverrides.string(_root.$meta, 'newUsers', {}) ?? 'Yeni Kullanıcılar';
	@override String get noNewUsers => TranslationOverrides.string(_root.$meta, 'noNewUsers', {}) ?? 'Yeni kullanıcı yok.';
	@override String get unnamed => TranslationOverrides.string(_root.$meta, 'unnamed', {}) ?? 'İsimsiz';
	@override String get unnamedUser => TranslationOverrides.string(_root.$meta, 'unnamedUser', {}) ?? 'İsimsiz Kullanıcı';
	@override String get joined => TranslationOverrides.string(_root.$meta, 'joined', {}) ?? 'Katıldı';
	@override String get dailyRevenue => TranslationOverrides.string(_root.$meta, 'dailyRevenue', {}) ?? 'Günlük gelir';
	@override String get last7DaysRevenueOrders => TranslationOverrides.string(_root.$meta, 'last7DaysRevenueOrders', {}) ?? 'Son 7 Gün - Gelir & Siparişler';
	@override String get orderStatuses => TranslationOverrides.string(_root.$meta, 'orderStatuses', {}) ?? 'Sipariş Durumları';
	@override String get last7DaysNewUsers => TranslationOverrides.string(_root.$meta, 'last7DaysNewUsers', {}) ?? 'Son 7 Gün - Yeni Kullanıcılar';
	@override String get dailyNewUsers => TranslationOverrides.string(_root.$meta, 'dailyNewUsers', {}) ?? 'Günlük yeni kullanıcı';
	@override String get last7DaysNewProducts => TranslationOverrides.string(_root.$meta, 'last7DaysNewProducts', {}) ?? 'Son 7 Gün - Yeni Ürünler';
	@override String get dailyNewProducts => TranslationOverrides.string(_root.$meta, 'dailyNewProducts', {}) ?? 'Günlük yeni ürün';
	@override String get ordersShort => TranslationOverrides.string(_root.$meta, 'ordersShort', {}) ?? 'sip.';
	@override String get dayAbbr => TranslationOverrides.string(_root.$meta, 'dayAbbr', {}) ?? 'Gün';
	@override String get unexpectedError => TranslationOverrides.string(_root.$meta, 'unexpectedError', {}) ?? 'Beklenmeyen bir hata oluştu.';
	@override String get errorPrefix => TranslationOverrides.string(_root.$meta, 'errorPrefix', {}) ?? 'Hata: ';
	@override String get noUsersFound => TranslationOverrides.string(_root.$meta, 'noUsersFound', {}) ?? 'Kullanıcı bulunamadı.';
	@override String get noEmail => TranslationOverrides.string(_root.$meta, 'noEmail', {}) ?? 'E-posta yok';
	@override String get rolePrefix => TranslationOverrides.string(_root.$meta, 'rolePrefix', {}) ?? 'Rol: ';
	@override String get searchProductsHint => TranslationOverrides.string(_root.$meta, 'searchProductsHint', {}) ?? 'Ürün ara...';
	@override String get sortByDate => TranslationOverrides.string(_root.$meta, 'sortByDate', {}) ?? 'Tarihe Göre Sırala';
	@override String get sortByPopularity => TranslationOverrides.string(_root.$meta, 'sortByPopularity', {}) ?? 'Popülerliğe Göre Sırala';
	@override String get sortByPrice => TranslationOverrides.string(_root.$meta, 'sortByPrice', {}) ?? 'Fiyata Göre Sırala';
	@override String get filters => TranslationOverrides.string(_root.$meta, 'filters', {}) ?? 'Filtreler';
	@override String get mainCategory => TranslationOverrides.string(_root.$meta, 'mainCategory', {}) ?? 'Ana Kategori';
	@override String get subCategory => TranslationOverrides.string(_root.$meta, 'subCategory', {}) ?? 'Alt Kategori';
	@override String get specificCategory => TranslationOverrides.string(_root.$meta, 'specificCategory', {}) ?? 'Özel Kategori';
	@override String get shoeSizes => TranslationOverrides.string(_root.$meta, 'shoeSizes', {}) ?? 'Ayakkabı Numaraları';
	@override String get sizeAgeGroups => TranslationOverrides.string(_root.$meta, 'sizeAgeGroups', {}) ?? 'Beden / Yaş Grupları';
	@override String get brands => TranslationOverrides.string(_root.$meta, 'brands', {}) ?? 'Markalar';
	@override String get addNewProduct => TranslationOverrides.string(_root.$meta, 'addNewProduct', {}) ?? 'Yeni Ürün Ekle';
	@override String get editProduct => TranslationOverrides.string(_root.$meta, 'editProduct', {}) ?? 'Ürünü Düzenle';
	@override String get retry => TranslationOverrides.string(_root.$meta, 'retry', {}) ?? 'Tekrar Dene';
	@override String get savingChanges => TranslationOverrides.string(_root.$meta, 'savingChanges', {}) ?? 'Değişiklikler Kaydediliyor...';
	@override String get addingProduct => TranslationOverrides.string(_root.$meta, 'addingProduct', {}) ?? 'Ürün Ekleniyor...';
	@override String get productUpdatedSuccess => TranslationOverrides.string(_root.$meta, 'productUpdatedSuccess', {}) ?? 'Ürün Başarıyla Güncellendi!';
	@override String get productAddedSuccess => TranslationOverrides.string(_root.$meta, 'productAddedSuccess', {}) ?? 'Ürün Başarıyla Eklendi!';
	@override String get addAnotherProduct => TranslationOverrides.string(_root.$meta, 'addAnotherProduct', {}) ?? 'Başka Ürün Ekle';
	@override String get goToProducts => TranslationOverrides.string(_root.$meta, 'goToProducts', {}) ?? 'Ürünlere Git';
	@override String get productName => TranslationOverrides.string(_root.$meta, 'productName', {}) ?? 'Ürün Adı';
	@override String get description => TranslationOverrides.string(_root.$meta, 'description', {}) ?? 'Açıklama';
	@override String get price => TranslationOverrides.string(_root.$meta, 'price', {}) ?? 'Fiyat';
	@override String get sku => TranslationOverrides.string(_root.$meta, 'sku', {}) ?? 'SKU (Stok Kodu)';
	@override String get stockQuantity => TranslationOverrides.string(_root.$meta, 'stockQuantity', {}) ?? 'Stok Miktarı';
	@override String get selectShoeSizes => TranslationOverrides.string(_root.$meta, 'selectShoeSizes', {}) ?? 'Ayakkabı Numarası Seçin';
	@override String get selectSizeAgeGroups => TranslationOverrides.string(_root.$meta, 'selectSizeAgeGroups', {}) ?? 'Beden / Yaş Grubu Seçin';
	@override String get brand => TranslationOverrides.string(_root.$meta, 'brand', {}) ?? 'Marka';
	@override String get saveChanges => TranslationOverrides.string(_root.$meta, 'saveChanges', {}) ?? 'Değişiklikleri Kaydet';
	@override String get addProduct => TranslationOverrides.string(_root.$meta, 'addProduct', {}) ?? 'Ürün Ekle';
	@override String get pleaseSelectA => TranslationOverrides.string(_root.$meta, 'pleaseSelectA', {}) ?? 'Lütfen seçiniz: ';
	@override String get pickImage => TranslationOverrides.string(_root.$meta, 'pickImage', {}) ?? 'Resim Seç';
	@override String get pleaseEnterA => TranslationOverrides.string(_root.$meta, 'pleaseEnterA', {}) ?? 'Lütfen giriniz: ';
	@override String get addNewBrandTitle => TranslationOverrides.string(_root.$meta, 'addNewBrandTitle', {}) ?? 'Yeni Marka Ekle';
	@override String get enterBrandName => TranslationOverrides.string(_root.$meta, 'enterBrandName', {}) ?? 'Marka adı giriniz';
	@override String get errorSelectCategoryBrand => TranslationOverrides.string(_root.$meta, 'errorSelectCategoryBrand', {}) ?? 'Lütfen bir kategori ve marka seçin.';
	@override String get errorSelectImage => TranslationOverrides.string(_root.$meta, 'errorSelectImage', {}) ?? 'Lütfen bir resim seçin.';
	@override String get errorStorageBucketMissing => TranslationOverrides.string(_root.$meta, 'errorStorageBucketMissing', {}) ?? 'Ürün kaydedilemedi: Depolama alanı \'products\' bulunamadı. Lütfen Supabase projenizde oluşturun.';
	@override String get errorStorage => TranslationOverrides.string(_root.$meta, 'errorStorage', {}) ?? 'Ürün kaydedilemedi: Depolama hatası: ';
	@override String get errorSaveProduct => TranslationOverrides.string(_root.$meta, 'errorSaveProduct', {}) ?? 'Ürün kaydedilemedi: ';
	@override String get noOrdersFound => TranslationOverrides.string(_root.$meta, 'noOrdersFound', {}) ?? 'Sipariş bulunamadı.';
	@override String get userPrefix => TranslationOverrides.string(_root.$meta, 'userPrefix', {}) ?? 'Kullanıcı: ';
	@override String get totalPrefix => TranslationOverrides.string(_root.$meta, 'totalPrefix', {}) ?? 'Toplam: \$';
	@override String get adminSettings => TranslationOverrides.string(_root.$meta, 'adminSettings', {}) ?? 'Yönetici Ayarları';
	@override String get adminInformation => TranslationOverrides.string(_root.$meta, 'adminInformation', {}) ?? 'Yönetici Bilgileri';
	@override String get emailLabel => TranslationOverrides.string(_root.$meta, 'emailLabel', {}) ?? 'E-posta:';
	@override String get fullNameLabel => TranslationOverrides.string(_root.$meta, 'fullNameLabel', {}) ?? 'Tam Ad:';
	@override String get roleLabel => TranslationOverrides.string(_root.$meta, 'roleLabel', {}) ?? 'Rol:';
	@override String get memberSinceLabel => TranslationOverrides.string(_root.$meta, 'memberSinceLabel', {}) ?? 'Üyelik Tarihi:';
	@override String get adminNotLoggedIn => TranslationOverrides.string(_root.$meta, 'adminNotLoggedIn', {}) ?? 'Yönetici girişi yapılmamış.';
	@override String get errorLoadAdminInfo => TranslationOverrides.string(_root.$meta, 'errorLoadAdminInfo', {}) ?? 'Yönetici bilgileri yüklenemedi: ';
	@override String get somethingWentWrong => TranslationOverrides.string(_root.$meta, 'somethingWentWrong', {}) ?? 'Bir şeyler ters gitti.';
	@override String get noProductsForSelection => TranslationOverrides.string(_root.$meta, 'noProductsForSelection', {}) ?? 'Bu seçim için ürün bulunamadı.';
	@override String get productDetail => TranslationOverrides.string(_root.$meta, 'productDetail', {}) ?? 'Ürün Detayı';
	@override String get reviewsCount => TranslationOverrides.string(_root.$meta, 'reviewsCount', {}) ?? 'Yorumlar ({count})';
	@override String get noReviewsYet => TranslationOverrides.string(_root.$meta, 'noReviewsYet', {}) ?? 'Henüz yorum yok.';
	@override String get emailCannotBeChanged => TranslationOverrides.string(_root.$meta, 'emailCannotBeChanged', {}) ?? '* E-posta adresi buradan doğrudan değiştirilemez.';
	@override String get genderMale => TranslationOverrides.string(_root.$meta, 'genderMale', {}) ?? 'Erkek';
	@override String get genderFemale => TranslationOverrides.string(_root.$meta, 'genderFemale', {}) ?? 'Kadın';
	@override String get genderOther => TranslationOverrides.string(_root.$meta, 'genderOther', {}) ?? 'Diğer';
	@override String get genderPreferNotToSay => TranslationOverrides.string(_root.$meta, 'genderPreferNotToSay', {}) ?? 'Belirtmek istemiyorum';
	@override String get loginToViewInfo => TranslationOverrides.string(_root.$meta, 'loginToViewInfo', {}) ?? 'Bilgileri görmek için lütfen giriş yapın.';
	@override String get selectCountryFirst => TranslationOverrides.string(_root.$meta, 'selectCountryFirst', {}) ?? 'Önce Ülke Seçin';
	@override String get selectCity => TranslationOverrides.string(_root.$meta, 'selectCity', {}) ?? 'Şehir Seçin';
	@override String get loginToManageAddresses => TranslationOverrides.string(_root.$meta, 'loginToManageAddresses', {}) ?? 'Adresleri yönetmek için lütfen giriş yapın.';
	@override String get loginToViewFavorites => TranslationOverrides.string(_root.$meta, 'loginToViewFavorites', {}) ?? 'Favorilerinizi görmek için lütfen giriş yapın.';
	@override String get selectPrefix => TranslationOverrides.string(_root.$meta, 'selectPrefix', {}) ?? 'Seçiniz: ';
	@override String get failedChangePassword => TranslationOverrides.string(_root.$meta, 'failedChangePassword', {}) ?? 'Şifre değiştirilemedi. Lütfen girişlerinizi kontrol edin.';
	@override String get onboarding => TranslationOverrides.string(_root.$meta, 'onboarding', {}) ?? 'Karşılama';
	@override String get onboardingScreen => TranslationOverrides.string(_root.$meta, 'onboardingScreen', {}) ?? 'Karşılama Ekranı';
	@override String get goToHome => TranslationOverrides.string(_root.$meta, 'goToHome', {}) ?? 'Ana Sayfaya Git';
	@override String get password => TranslationOverrides.string(_root.$meta, 'password', {}) ?? 'Şifre';
	@override String get confirmPassword => TranslationOverrides.string(_root.$meta, 'confirmPassword', {}) ?? 'Şifreyi Onayla';
	@override String get logoutSuccess => TranslationOverrides.string(_root.$meta, 'logoutSuccess', {}) ?? 'Başarıyla çıkış yapıldı!';
	@override String get addedToFavorites => TranslationOverrides.string(_root.$meta, 'addedToFavorites', {}) ?? 'Favorilere eklendi!';
	@override String get removedFromFavorites => TranslationOverrides.string(_root.$meta, 'removedFromFavorites', {}) ?? 'Favorilerden çıkarıldı.';
	@override String get wishlistUpdateFailed => TranslationOverrides.string(_root.$meta, 'wishlistUpdateFailed', {}) ?? 'İstek listesi güncellenemedi. Lütfen tekrar deneyin.';
	@override String get filterAll => TranslationOverrides.string(_root.$meta, 'filterAll', {}) ?? 'Tümü';
	@override String get filterVerified => TranslationOverrides.string(_root.$meta, 'filterVerified', {}) ?? 'Doğrulanmış Satın Alma';
	@override String get filterProductRating => TranslationOverrides.string(_root.$meta, 'filterProductRating', {}) ?? 'Ürün Puanı';
	@override String get filterDeliveryRating => TranslationOverrides.string(_root.$meta, 'filterDeliveryRating', {}) ?? 'Teslimat Puanı';
	@override String get filterWithComment => TranslationOverrides.string(_root.$meta, 'filterWithComment', {}) ?? 'Yorumlu';
	@override String get haveACoupon => TranslationOverrides.string(_root.$meta, 'haveACoupon', {}) ?? 'Kuponunuz var mı?';
	@override String get enterCouponCode => TranslationOverrides.string(_root.$meta, 'enterCouponCode', {}) ?? 'Kupon kodunu girin';
	@override String get applyCoupon => TranslationOverrides.string(_root.$meta, 'applyCoupon', {}) ?? 'Uygula';
	@override String get removeCoupon => TranslationOverrides.string(_root.$meta, 'removeCoupon', {}) ?? 'Kuponu Kaldır';
	@override String get discount => TranslationOverrides.string(_root.$meta, 'discount', {}) ?? 'İndirim';
	@override String get couponRemoved => TranslationOverrides.string(_root.$meta, 'couponRemoved', {}) ?? 'Kupon kaldırıldı.';
	@override String get couponAppliedSuccessfully => TranslationOverrides.string(_root.$meta, 'couponAppliedSuccessfully', {}) ?? 'Kupon başarıyla uygulandı!';
	@override String get invalidCouponCode => TranslationOverrides.string(_root.$meta, 'invalidCouponCode', {}) ?? 'Geçersiz kupon kodu.';
	@override String get couponNotActive => TranslationOverrides.string(_root.$meta, 'couponNotActive', {}) ?? 'Kupon aktif değil.';
	@override String get couponExpired => TranslationOverrides.string(_root.$meta, 'couponExpired', {}) ?? 'Kuponun süresi doldu.';
	@override String get couponLimitReached => TranslationOverrides.string(_root.$meta, 'couponLimitReached', {}) ?? 'Kupon kullanım sınırı aşıldı.';
	@override String get minimumPurchaseRequired => TranslationOverrides.string(_root.$meta, 'minimumPurchaseRequired', {}) ?? 'Minimum {amount} tutarında alışveriş gerekli.';
	@override String get confirmLogoutMessage => TranslationOverrides.string(_root.$meta, 'confirmLogoutMessage', {}) ?? 'Çıkış yapmak istediğinizden emin misiniz?';
	@override String get welcomeBackLogin => TranslationOverrides.string(_root.$meta, 'welcomeBackLogin', {}) ?? 'Tekrar hoş geldiniz! Giriş başarılı.';
	@override String get seeAll => TranslationOverrides.string(_root.$meta, 'seeAll', {}) ?? 'Tümünü gör';
	@override String get recommendedForYou => TranslationOverrides.string(_root.$meta, 'recommendedForYou', {}) ?? 'Sizin için önerilenler';
	@override String get shopByBrand => TranslationOverrides.string(_root.$meta, 'shopByBrand', {}) ?? 'Markaya göre alışveriş';
	@override String get collections => TranslationOverrides.string(_root.$meta, 'collections', {}) ?? 'Koleksiyonlar';
	@override String get collection => TranslationOverrides.string(_root.$meta, 'collection', {}) ?? 'Koleksiyon';
	@override String get addedToFavoritesCategory => TranslationOverrides.string(_root.$meta, 'addedToFavoritesCategory', {}) ?? 'Favorilere eklendi';
	@override String get removedFromFavoritesCategory => TranslationOverrides.string(_root.$meta, 'removedFromFavoritesCategory', {}) ?? 'Favorilerden çıkarıldı';
	@override String get undo => TranslationOverrides.string(_root.$meta, 'undo', {}) ?? 'Geri al';
	@override String get loginToViewCart => TranslationOverrides.string(_root.$meta, 'loginToViewCart', {}) ?? 'Sepetinizi görmek için giriş yapın.';
	@override String get loginToAddToCart => TranslationOverrides.string(_root.$meta, 'loginToAddToCart', {}) ?? 'Sepete ürün eklemek için giriş yapın.';
	@override String get loginToAddToFavorites => TranslationOverrides.string(_root.$meta, 'loginToAddToFavorites', {}) ?? 'Favorilere eklemek için giriş yapmalısınız.';
	@override String get categoryAddedToFavorites => TranslationOverrides.string(_root.$meta, 'categoryAddedToFavorites', {}) ?? '{name} favorilerinize eklendi';
	@override String get categoryRemovedFromFavorites => TranslationOverrides.string(_root.$meta, 'categoryRemovedFromFavorites', {}) ?? '{name} favorilerinizden çıkarıldı';
	@override String get removedFromCart => TranslationOverrides.string(_root.$meta, 'removedFromCart', {}) ?? 'Sepetten çıkarıldı';
	@override String get brandAddedToFavorites => TranslationOverrides.string(_root.$meta, 'brandAddedToFavorites', {}) ?? 'Marka favorilere eklendi';
	@override String get brandRemovedFromFavorites => TranslationOverrides.string(_root.$meta, 'brandRemovedFromFavorites', {}) ?? 'Marka favorilerden çıkarıldı';
	@override String get endsIn => TranslationOverrides.string(_root.$meta, 'endsIn', {}) ?? 'Bitiş';
	@override String get specialOffer => TranslationOverrides.string(_root.$meta, 'specialOffer', {}) ?? 'Özel Teklif';
	@override String get limitedTimeOffer => TranslationOverrides.string(_root.$meta, 'limitedTimeOffer', {}) ?? 'Sınırlı süre teklifi';
	@override String get dealsOfTheDay => TranslationOverrides.string(_root.$meta, 'dealsOfTheDay', {}) ?? 'Günün Fırsatları';
	@override String get flashSale => TranslationOverrides.string(_root.$meta, 'flashSale', {}) ?? 'Flaş İndirim';
	@override String get checkoutTitle => TranslationOverrides.string(_root.$meta, 'checkoutTitle', {}) ?? 'Ödeme';
	@override String get stepAddress => TranslationOverrides.string(_root.$meta, 'stepAddress', {}) ?? 'Adres';
	@override String get stepShipping => TranslationOverrides.string(_root.$meta, 'stepShipping', {}) ?? 'Kargo';
	@override String get stepPayment => TranslationOverrides.string(_root.$meta, 'stepPayment', {}) ?? 'Ödeme';
	@override String get stepSummary => TranslationOverrides.string(_root.$meta, 'stepSummary', {}) ?? 'Özet';
	@override String get continueButton => TranslationOverrides.string(_root.$meta, 'continueButton', {}) ?? 'Devam';
	@override String get backButton => TranslationOverrides.string(_root.$meta, 'backButton', {}) ?? 'Geri';
	@override String get placeOrder => TranslationOverrides.string(_root.$meta, 'placeOrder', {}) ?? 'Siparişi Ver';
	@override String get orderPlacedTitle => TranslationOverrides.string(_root.$meta, 'orderPlacedTitle', {}) ?? 'Sipariş Alındı!';
	@override String get orderPlacedDescription => TranslationOverrides.string(_root.$meta, 'orderPlacedDescription', {}) ?? 'Siparişiniz alındı.';
	@override String get backToHome => TranslationOverrides.string(_root.$meta, 'backToHome', {}) ?? 'Ana Sayfaya Dön';
	@override String get fillRequiredFields => TranslationOverrides.string(_root.$meta, 'fillRequiredFields', {}) ?? 'Lütfen zorunlu alanları doldurun.';
	@override String get selectShippingMethod => TranslationOverrides.string(_root.$meta, 'selectShippingMethod', {}) ?? 'Lütfen kargo yöntemi seçin.';
	@override String get selectPaymentMethod => TranslationOverrides.string(_root.$meta, 'selectPaymentMethod', {}) ?? 'Lütfen ödeme yöntemi seçin.';
	@override String get firstName => TranslationOverrides.string(_root.$meta, 'firstName', {}) ?? 'Ad';
	@override String get lastName => TranslationOverrides.string(_root.$meta, 'lastName', {}) ?? 'Soyad';
	@override String get addressLine1 => TranslationOverrides.string(_root.$meta, 'addressLine1', {}) ?? 'Adres';
	@override String get sameAsBilling => TranslationOverrides.string(_root.$meta, 'sameAsBilling', {}) ?? 'Fatura adresi ile aynı';
	@override String get deleteAccount => TranslationOverrides.string(_root.$meta, 'deleteAccount', {}) ?? 'Hesabı Sil';
	@override String get deleteAccountTitle => TranslationOverrides.string(_root.$meta, 'deleteAccountTitle', {}) ?? 'Hesabı Sil?';
	@override String get deleteAccountMessage30Days => TranslationOverrides.string(_root.$meta, 'deleteAccountMessage30Days', {}) ?? 'Hesabınız silinmek üzere planlanacaktır. 30 gün içinde kalıcı olarak silinecektir. Bu süre içinde tekrar giriş yaparak iptal edebilirsiniz.';
	@override String get deleteAccountWhatWillBeDeleted => TranslationOverrides.string(_root.$meta, 'deleteAccountWhatWillBeDeleted', {}) ?? 'Kalıcı olarak silinecekler:';
	@override String get deleteAccountItemProfile => TranslationOverrides.string(_root.$meta, 'deleteAccountItemProfile', {}) ?? 'Profiliniz ve kişisel bilgileriniz';
	@override String get deleteAccountItemOrders => TranslationOverrides.string(_root.$meta, 'deleteAccountItemOrders', {}) ?? 'Tüm siparişleriniz ve sipariş geçmişiniz';
	@override String get deleteAccountItemAddresses => TranslationOverrides.string(_root.$meta, 'deleteAccountItemAddresses', {}) ?? 'Kayıtlı adresleriniz';
	@override String get deleteAccountItemReviews => TranslationOverrides.string(_root.$meta, 'deleteAccountItemReviews', {}) ?? 'Tüm yorumlarınız ve puanlarınız';
	@override String get deleteAccountCannotUndo => TranslationOverrides.string(_root.$meta, 'deleteAccountCannotUndo', {}) ?? '30 gün sonra bu işlem geri alınamaz. 30 gün içinde giriş yaparak iptal edebilirsiniz.';
	@override String get deleteAccountContinue => TranslationOverrides.string(_root.$meta, 'deleteAccountContinue', {}) ?? 'Devam';
	@override String get deleteAccountGoBack => TranslationOverrides.string(_root.$meta, 'deleteAccountGoBack', {}) ?? 'Geri';
	@override String get deleteAccountFinalConfirm => TranslationOverrides.string(_root.$meta, 'deleteAccountFinalConfirm', {}) ?? 'Son Onay';
	@override String get deleteAccountSure => TranslationOverrides.string(_root.$meta, 'deleteAccountSure', {}) ?? 'Hesap silme işlemini planlamak istediğinize emin misiniz?';
	@override String get deleteAccountEmailLabel => TranslationOverrides.string(_root.$meta, 'deleteAccountEmailLabel', {}) ?? 'Hesap: {email}';
	@override String get deleteAccountUnderstandPermanent => TranslationOverrides.string(_root.$meta, 'deleteAccountUnderstandPermanent', {}) ?? 'Hesabımın 30 gün içinde silineceğini ve bu süre içinde giriş yaparak iptal edebileceğimi anlıyorum';
	@override String get deleteMyAccount => TranslationOverrides.string(_root.$meta, 'deleteMyAccount', {}) ?? 'Hesabımı Sil';
	@override String get deleteAccountSuccess => TranslationOverrides.string(_root.$meta, 'deleteAccountSuccess', {}) ?? 'Hesap silme planlandı. Hesabınız 30 gün içinde kaldırılacaktır. İptal etmek için bu süre içinde giriş yapabilirsiniz.';
	@override String get deleteAccountFailed => TranslationOverrides.string(_root.$meta, 'deleteAccountFailed', {}) ?? 'Hesap silme planlanamadı. Lütfen tekrar deneyin veya destek ile iletişime geçin.';
	@override String get selectAddress => TranslationOverrides.string(_root.$meta, 'selectAddress', {}) ?? 'Adres Seçin';
	@override String get addNewAddress => TranslationOverrides.string(_root.$meta, 'addNewAddress', {}) ?? 'Yeni Adres Ekle';
	@override String get billingAddress => TranslationOverrides.string(_root.$meta, 'billingAddress', {}) ?? 'Fatura Adresi';
	@override String get newAddress => TranslationOverrides.string(_root.$meta, 'newAddress', {}) ?? 'Yeni Adres';
	@override String get defaultAddress => TranslationOverrides.string(_root.$meta, 'defaultAddress', {}) ?? 'Varsayılan';
	@override String get addressAdded => TranslationOverrides.string(_root.$meta, 'addressAdded', {}) ?? 'Adres başarıyla eklendi!';
	@override String get addressDeleted => TranslationOverrides.string(_root.$meta, 'addressDeleted', {}) ?? 'Adres başarıyla silindi!';
	@override String get defaultAddressSet => TranslationOverrides.string(_root.$meta, 'defaultAddressSet', {}) ?? 'Varsayılan adres başarıyla ayarlandı!';
	@override String get addressLabelHint => TranslationOverrides.string(_root.$meta, 'addressLabelHint', {}) ?? 'örn. Ev, Ofis';
	@override String get confirmDeleteAddress => TranslationOverrides.string(_root.$meta, 'confirmDeleteAddress', {}) ?? 'Bu adresi silmek istediğinize emin misiniz?';
	@override String get optional => TranslationOverrides.string(_root.$meta, 'optional', {}) ?? 'İsteğe bağlı';
	@override String get setAsDefault => TranslationOverrides.string(_root.$meta, 'setAsDefault', {}) ?? 'Varsayılan Yap';
	@override String get editAddress => TranslationOverrides.string(_root.$meta, 'editAddress', {}) ?? 'Adresi Düzenle';
	@override String get addAddress => TranslationOverrides.string(_root.$meta, 'addAddress', {}) ?? 'Adres Ekle';
	@override String get errorOccurred => TranslationOverrides.string(_root.$meta, 'errorOccurred', {}) ?? 'Bir hata oluştu. Lütfen tekrar deneyin.';
	@override String get delete => TranslationOverrides.string(_root.$meta, 'delete', {}) ?? 'Sil';
	@override String get currency => TranslationOverrides.string(_root.$meta, 'currency', {}) ?? 'Currency';
	@override String get contactUs => TranslationOverrides.string(_root.$meta, 'contactUs', {}) ?? 'Contact us';
	@override String get contactUsBody => TranslationOverrides.string(_root.$meta, 'contactUsBody', {}) ?? 'Email: support@masterfabric.co\nPhone: +90 212 000 00 00';
	@override String get faq => TranslationOverrides.string(_root.$meta, 'faq', {}) ?? 'FAQ';
	@override String get faqBody => TranslationOverrides.string(_root.$meta, 'faqBody', {}) ?? 'Frequently asked questions and answers will be available here.';
	@override String get returnsAndRefunds => TranslationOverrides.string(_root.$meta, 'returnsAndRefunds', {}) ?? 'Returns & refunds';
	@override String get returnsAndRefundsBody => TranslationOverrides.string(_root.$meta, 'returnsAndRefundsBody', {}) ?? 'Please check our return policy in the product detail page (Cancellation & returns).';
	@override String get generalSettings => TranslationOverrides.string(_root.$meta, 'generalSettings', {}) ?? 'General settings';
	@override String get generalSettingsDescription => TranslationOverrides.string(_root.$meta, 'generalSettingsDescription', {}) ?? 'Common store options. Values are saved in admin_settings table.';
	@override String get storeSettingsKeyValue => TranslationOverrides.string(_root.$meta, 'storeSettingsKeyValue', {}) ?? 'Store settings (key-value)';
	@override String get storeSettingsKeyValueDescription => TranslationOverrides.string(_root.$meta, 'storeSettingsKeyValueDescription', {}) ?? 'All key-value pairs from admin_settings. Tap a row to edit value, or add a new key (e.g. maintenance_mode, guest_checkout_enabled).';
	@override String get maintenanceMode => TranslationOverrides.string(_root.$meta, 'maintenanceMode', {}) ?? 'Maintenance mode';
	@override String get maintenanceModeSubtitle => TranslationOverrides.string(_root.$meta, 'maintenanceModeSubtitle', {}) ?? 'When on, store can show a maintenance message to customers.';
	@override String get guestCheckout => TranslationOverrides.string(_root.$meta, 'guestCheckout', {}) ?? 'Guest checkout';
	@override String get guestCheckoutSubtitle => TranslationOverrides.string(_root.$meta, 'guestCheckoutSubtitle', {}) ?? 'Allow checkout without creating an account.';
	@override String get defaultCurrency => TranslationOverrides.string(_root.$meta, 'defaultCurrency', {}) ?? 'Default currency';
	@override String get defaultCurrencySubtitle => TranslationOverrides.string(_root.$meta, 'defaultCurrencySubtitle', {}) ?? 'Shown as store default on the main app. Used when user has not chosen a currency.';
	@override String get addSetting => TranslationOverrides.string(_root.$meta, 'addSetting', {}) ?? 'Add setting';
	@override String get noStoreSettingsYet => TranslationOverrides.string(_root.$meta, 'noStoreSettingsYet', {}) ?? 'No store settings yet.';
	@override String get addKeyValueSetting => TranslationOverrides.string(_root.$meta, 'addKeyValueSetting', {}) ?? 'Add key-value setting';
	@override String get addSettingDialogDescription => TranslationOverrides.string(_root.$meta, 'addSettingDialogDescription', {}) ?? 'Add a new setting stored in admin_settings. Key is unique (e.g. maintenance_mode). Value can be text or true/false.';
	@override String get keyLabel => TranslationOverrides.string(_root.$meta, 'keyLabel', {}) ?? 'Key';
	@override String get valueLabel => TranslationOverrides.string(_root.$meta, 'valueLabel', {}) ?? 'Value';
	@override String get add => TranslationOverrides.string(_root.$meta, 'add', {}) ?? 'Add';
	@override String get sessions => TranslationOverrides.string(_root.$meta, 'sessions', {}) ?? 'Sessions';
	@override String get activityLog => TranslationOverrides.string(_root.$meta, 'activityLog', {}) ?? 'Activity log';
	@override String get moderation => TranslationOverrides.string(_root.$meta, 'moderation', {}) ?? 'Moderation';
	@override String get staff => TranslationOverrides.string(_root.$meta, 'staff', {}) ?? 'Staff';
	@override String get reports => TranslationOverrides.string(_root.$meta, 'reports', {}) ?? 'Reports';
	@override String get appConfig => TranslationOverrides.string(_root.$meta, 'appConfig', {}) ?? 'App config';
	@override String get homeAppBarTitle => TranslationOverrides.string(_root.$meta, 'homeAppBarTitle', {}) ?? 'Masterfabric S Store';
	@override String get quickAccess => TranslationOverrides.string(_root.$meta, 'quickAccess', {}) ?? 'Quick access';
	@override String get productReviews => TranslationOverrides.string(_root.$meta, 'productReviews', {}) ?? 'Product reviews';
	@override String get userAddresses => TranslationOverrides.string(_root.$meta, 'userAddresses', {}) ?? 'User addresses';
	@override String get addresses => TranslationOverrides.string(_root.$meta, 'addresses', {}) ?? 'Addresses';
	@override String get options => TranslationOverrides.string(_root.$meta, 'options', {}) ?? 'Options';
	@override String get details => TranslationOverrides.string(_root.$meta, 'details', {}) ?? 'Details';
	@override String get active => TranslationOverrides.string(_root.$meta, 'active', {}) ?? 'Active';
	@override String get inactive => TranslationOverrides.string(_root.$meta, 'inactive', {}) ?? 'Inactive';
	@override String get deactivate => TranslationOverrides.string(_root.$meta, 'deactivate', {}) ?? 'Deactivate';
	@override String get activate => TranslationOverrides.string(_root.$meta, 'activate', {}) ?? 'Activate';
	@override String get pending => TranslationOverrides.string(_root.$meta, 'pending', {}) ?? 'Pending';
	@override String get approved => TranslationOverrides.string(_root.$meta, 'approved', {}) ?? 'Approved';
	@override String get rejected => TranslationOverrides.string(_root.$meta, 'rejected', {}) ?? 'Rejected';
	@override String get approve => TranslationOverrides.string(_root.$meta, 'approve', {}) ?? 'Approve';
	@override String get reject => TranslationOverrides.string(_root.$meta, 'reject', {}) ?? 'Reject';
	@override String get unapprove => TranslationOverrides.string(_root.$meta, 'unapprove', {}) ?? 'Unapprove';
	@override String get unknownProduct => TranslationOverrides.string(_root.$meta, 'unknownProduct', {}) ?? 'Unknown product';
	@override String get unknownAdmin => TranslationOverrides.string(_root.$meta, 'unknownAdmin', {}) ?? 'Unknown admin';
	@override String get unknown => TranslationOverrides.string(_root.$meta, 'unknown', {}) ?? 'Unknown';
	@override String get saved => TranslationOverrides.string(_root.$meta, 'saved', {}) ?? 'Saved';
	@override String get date => TranslationOverrides.string(_root.$meta, 'date', {}) ?? 'Date';
	@override String get revenue => TranslationOverrides.string(_root.$meta, 'revenue', {}) ?? 'Revenue';
	@override String get sale => TranslationOverrides.string(_root.$meta, 'sale', {}) ?? 'SALE';
	@override String get flash => TranslationOverrides.string(_root.$meta, 'flash', {}) ?? 'FLASH';
	@override String get weekStar => TranslationOverrides.string(_root.$meta, 'weekStar', {}) ?? 'WEEK STAR';
	@override String get user => TranslationOverrides.string(_root.$meta, 'user', {}) ?? 'User';
	@override String get createNewCollection => TranslationOverrides.string(_root.$meta, 'createNewCollection', {}) ?? 'Create new collection';
	@override String get removeAll => TranslationOverrides.string(_root.$meta, 'removeAll', {}) ?? 'Remove all';
	@override String get createNewGroup => TranslationOverrides.string(_root.$meta, 'createNewGroup', {}) ?? 'Create New Group';
	@override String get groupName => TranslationOverrides.string(_root.$meta, 'groupName', {}) ?? 'Group Name';
	@override String get create => TranslationOverrides.string(_root.$meta, 'create', {}) ?? 'Create';
	@override String get deleteCollection => TranslationOverrides.string(_root.$meta, 'deleteCollection', {}) ?? 'Delete Collection';
	@override String get deleted => TranslationOverrides.string(_root.$meta, 'deleted', {}) ?? 'Deleted';
	@override String get collectionDeletedSuccessfully => TranslationOverrides.string(_root.$meta, 'collectionDeletedSuccessfully', {}) ?? 'Collection deleted successfully';
	@override String get noItemsInCollection => TranslationOverrides.string(_root.$meta, 'noItemsInCollection', {}) ?? 'No items in this collection yet';
	@override String get noOtherProductsToAdd => TranslationOverrides.string(_root.$meta, 'noOtherProductsToAdd', {}) ?? 'No other products to add';
	@override String get removed => TranslationOverrides.string(_root.$meta, 'removed', {}) ?? 'Removed';
	@override String get added => TranslationOverrides.string(_root.$meta, 'added', {}) ?? 'Added';
	@override String get anonymous => TranslationOverrides.string(_root.$meta, 'anonymous', {}) ?? 'Anonymous';
	@override String get appConfigCopiedToClipboard => TranslationOverrides.string(_root.$meta, 'appConfigCopiedToClipboard', {}) ?? 'App config copied to clipboard';
	@override String get noKeys => TranslationOverrides.string(_root.$meta, 'noKeys', {}) ?? 'No keys';
	@override String get noCouponsFound => TranslationOverrides.string(_root.$meta, 'noCouponsFound', {}) ?? 'No coupons found';
	@override String get addCoupon => TranslationOverrides.string(_root.$meta, 'addCoupon', {}) ?? 'Add Coupon';
	@override String get deleteCoupon => TranslationOverrides.string(_root.$meta, 'deleteCoupon', {}) ?? 'Delete Coupon';
	@override String get manageCoupon => TranslationOverrides.string(_root.$meta, 'manageCoupon', {}) ?? 'Manage Coupon';
	@override String get backToList => TranslationOverrides.string(_root.$meta, 'backToList', {}) ?? 'Back to List';
	@override String get couponCode => TranslationOverrides.string(_root.$meta, 'couponCode', {}) ?? 'Coupon Code';
	@override String get discountType => TranslationOverrides.string(_root.$meta, 'discountType', {}) ?? 'Discount Type';
	@override String get discountValue => TranslationOverrides.string(_root.$meta, 'discountValue', {}) ?? 'Discount Value';
	@override String get selectDate => TranslationOverrides.string(_root.$meta, 'selectDate', {}) ?? 'Select Date';
	@override String get isActive => TranslationOverrides.string(_root.$meta, 'isActive', {}) ?? 'Is Active';
	@override String get saveCoupon => TranslationOverrides.string(_root.$meta, 'saveCoupon', {}) ?? 'Save Coupon';
	@override String get couponSavedSuccessfully => TranslationOverrides.string(_root.$meta, 'couponSavedSuccessfully', {}) ?? 'Coupon saved successfully!';
	@override String get percentage => TranslationOverrides.string(_root.$meta, 'percentage', {}) ?? 'Percentage (%)';
	@override String get fixedAmount => TranslationOverrides.string(_root.$meta, 'fixedAmount', {}) ?? 'Fixed Amount (\$)';
	@override String get selectOptions => TranslationOverrides.string(_root.$meta, 'selectOptions', {}) ?? 'SELECT OPTIONS';
	@override String get previous => TranslationOverrides.string(_root.$meta, 'previous', {}) ?? 'PREVIOUS';
	@override String get next => TranslationOverrides.string(_root.$meta, 'next', {}) ?? 'NEXT';
	@override String get welcome => TranslationOverrides.string(_root.$meta, 'welcome', {}) ?? 'Welcome';
	@override String get discoverAmazingProducts => TranslationOverrides.string(_root.$meta, 'discoverAmazingProducts', {}) ?? 'Discover amazing products';
	@override String get easyShopping => TranslationOverrides.string(_root.$meta, 'easyShopping', {}) ?? 'Easy Shopping';
	@override String get browseAndBuyWithEase => TranslationOverrides.string(_root.$meta, 'browseAndBuyWithEase', {}) ?? 'Browse and buy with ease';
	@override String get fastDelivery => TranslationOverrides.string(_root.$meta, 'fastDelivery', {}) ?? 'Fast Delivery';
	@override String get getOrdersDeliveredQuickly => TranslationOverrides.string(_root.$meta, 'getOrdersDeliveredQuickly', {}) ?? 'Get your orders delivered quickly';
	@override String get skip => TranslationOverrides.string(_root.$meta, 'skip', {}) ?? 'Skip';
	@override String get getStarted => TranslationOverrides.string(_root.$meta, 'getStarted', {}) ?? 'Get Started';
	@override String get sortBy => TranslationOverrides.string(_root.$meta, 'sortBy', {}) ?? 'Sort by';
	@override String get selectHowToSortProducts => TranslationOverrides.string(_root.$meta, 'selectHowToSortProducts', {}) ?? 'Select how you want to sort the products';
	@override String get filterProductsByCategories => TranslationOverrides.string(_root.$meta, 'filterProductsByCategories', {}) ?? 'Filter products by categories, price, and more';
	@override String get clearFilters => TranslationOverrides.string(_root.$meta, 'clearFilters', {}) ?? 'Clear Filters';
	@override String get productAddedToCartTitle => TranslationOverrides.string(_root.$meta, 'productAddedToCartTitle', {}) ?? 'Product Added to Cart';
	@override String get items => TranslationOverrides.string(_root.$meta, 'items', {}) ?? 'Items';
	@override String get continueShopping => TranslationOverrides.string(_root.$meta, 'continueShopping', {}) ?? 'Continue Shopping';
	@override String get viewCart => TranslationOverrides.string(_root.$meta, 'viewCart', {}) ?? 'View Cart';
	@override String get failedToLoadCart => TranslationOverrides.string(_root.$meta, 'failedToLoadCart', {}) ?? 'Failed to load cart';
	@override String get deleteAddress => TranslationOverrides.string(_root.$meta, 'deleteAddress', {}) ?? 'Delete Address';
	@override String get defaultLabel => TranslationOverrides.string(_root.$meta, 'defaultLabel', {}) ?? 'Default';
	@override String get verified => TranslationOverrides.string(_root.$meta, 'verified', {}) ?? 'Verified';
	@override String get productFallback => TranslationOverrides.string(_root.$meta, 'productFallback', {}) ?? 'Product';
	@override String get removeItem => TranslationOverrides.string(_root.$meta, 'removeItem', {}) ?? 'Remove item';
	@override String get noImageAvailable => TranslationOverrides.string(_root.$meta, 'noImageAvailable', {}) ?? 'No Image Available';
	@override String get productDetails => TranslationOverrides.string(_root.$meta, 'productDetails', {}) ?? 'Product Details';
	@override String get pleaseSignInToManageFavorites => TranslationOverrides.string(_root.$meta, 'pleaseSignInToManageFavorites', {}) ?? 'Please sign in to manage favorites';
	@override String get comment => TranslationOverrides.string(_root.$meta, 'comment', {}) ?? 'Comment';
	@override String get delivery => TranslationOverrides.string(_root.$meta, 'delivery', {}) ?? 'Delivery';
	@override String get relatedProducts => TranslationOverrides.string(_root.$meta, 'relatedProducts', {}) ?? 'Related Products';
	@override String get peopleAlsoViewed => TranslationOverrides.string(_root.$meta, 'peopleAlsoViewed', {}) ?? 'People Also Viewed';
	@override String get removeItemTitle => TranslationOverrides.string(_root.$meta, 'removeItemTitle', {}) ?? 'Remove Item';
	@override String get discountCode => TranslationOverrides.string(_root.$meta, 'discountCode', {}) ?? 'Discount code';
	@override String get removeCouponTooltip => TranslationOverrides.string(_root.$meta, 'removeCouponTooltip', {}) ?? 'Remove coupon';
	@override String get shoppingCart => TranslationOverrides.string(_root.$meta, 'shoppingCart', {}) ?? 'Shopping Cart';
	@override String get refreshCart => TranslationOverrides.string(_root.$meta, 'refreshCart', {}) ?? 'Refresh cart';
	@override String get free => TranslationOverrides.string(_root.$meta, 'free', {}) ?? 'Free';
	@override String get standardShipping => TranslationOverrides.string(_root.$meta, 'standardShipping', {}) ?? 'Standard Shipping';
	@override String get deliveryToYourAddress => TranslationOverrides.string(_root.$meta, 'deliveryToYourAddress', {}) ?? 'Delivery to your address';
	@override String get expressShipping => TranslationOverrides.string(_root.$meta, 'expressShipping', {}) ?? 'Express Shipping';
	@override String get fastDeliveryDesc => TranslationOverrides.string(_root.$meta, 'fastDeliveryDesc', {}) ?? 'Fast delivery';
	@override String get freeShipping => TranslationOverrides.string(_root.$meta, 'freeShipping', {}) ?? 'Free Shipping';
	@override String get bankTransfer => TranslationOverrides.string(_root.$meta, 'bankTransfer', {}) ?? 'Bank Transfer';
	@override String get directBankTransfer => TranslationOverrides.string(_root.$meta, 'directBankTransfer', {}) ?? 'Direct bank transfer';
	@override String get cashOnDelivery => TranslationOverrides.string(_root.$meta, 'cashOnDelivery', {}) ?? 'Cash on Delivery';
	@override String get payWhenYouReceive => TranslationOverrides.string(_root.$meta, 'payWhenYouReceive', {}) ?? 'Pay when you receive';
	@override String get creditCard => TranslationOverrides.string(_root.$meta, 'creditCard', {}) ?? 'Credit Card';
	@override String get payWithCard => TranslationOverrides.string(_root.$meta, 'payWithCard', {}) ?? 'Pay with card';
	@override String get subtotal => TranslationOverrides.string(_root.$meta, 'subtotal', {}) ?? 'Subtotal';
	@override String get shipping => TranslationOverrides.string(_root.$meta, 'shipping', {}) ?? 'Shipping';
	@override String get tax => TranslationOverrides.string(_root.$meta, 'tax', {}) ?? 'Tax';
	@override String get dateNewest => TranslationOverrides.string(_root.$meta, 'dateNewest', {}) ?? 'Date (Newest)';
	@override String get dateOldest => TranslationOverrides.string(_root.$meta, 'dateOldest', {}) ?? 'Date (Oldest)';
	@override String get priceLowToHigh => TranslationOverrides.string(_root.$meta, 'priceLowToHigh', {}) ?? 'Price (Low to High)';
	@override String get priceHighToLow => TranslationOverrides.string(_root.$meta, 'priceHighToLow', {}) ?? 'Price (High to Low)';
	@override String get addressSingular => TranslationOverrides.string(_root.$meta, 'addressSingular', {}) ?? 'address';
	@override String get addressesPlural => TranslationOverrides.string(_root.$meta, 'addressesPlural', {}) ?? 'addresses';
	@override String get statusActiveInactive => TranslationOverrides.string(_root.$meta, 'statusActiveInactive', {}) ?? 'Status: {status}';
	@override String get confirmRemoveItemFromCart => TranslationOverrides.string(_root.$meta, 'confirmRemoveItemFromCart', {}) ?? 'Are you sure you want to remove "{name}" from your cart?';
	@override String get viewAppConfigJson => TranslationOverrides.string(_root.$meta, 'viewAppConfigJson', {}) ?? 'View app_config.json';
	@override String get revenueAndOrdersByPeriod => TranslationOverrides.string(_root.$meta, 'revenueAndOrdersByPeriod', {}) ?? 'Revenue & orders by period';
}

/// The flat map containing all translations for locale <tr>.
/// Only for edge cases! For simple maps, use the map function of this library.
///
/// The Dart AOT compiler has issues with very large switch statements,
/// so the map is split into smaller functions (512 entries each).
extension on TranslationsTr {
	dynamic _flatMapFunction(String path) {
		return switch (path) {
			'localLanguageCode' => TranslationOverrides.string(_root.$meta, 'localLanguageCode', {}) ?? 'tr_TR',
			'home' => TranslationOverrides.string(_root.$meta, 'home', {}) ?? 'Anasayfa',
			'categories' => TranslationOverrides.string(_root.$meta, 'categories', {}) ?? 'Kategoriler',
			'cart' => TranslationOverrides.string(_root.$meta, 'cart', {}) ?? 'Sepetim',
			'favorites' => TranslationOverrides.string(_root.$meta, 'favorites', {}) ?? 'Favorilerim',
			'profile' => TranslationOverrides.string(_root.$meta, 'profile', {}) ?? 'Profil',
			'myProfile' => TranslationOverrides.string(_root.$meta, 'myProfile', {}) ?? 'Profilim',
			'settings' => TranslationOverrides.string(_root.$meta, 'settings', {}) ?? 'Ayarlar',
			'search' => TranslationOverrides.string(_root.$meta, 'search', {}) ?? 'Ara',
			'apply' => TranslationOverrides.string(_root.$meta, 'apply', {}) ?? 'Uygula',
			'clear' => TranslationOverrides.string(_root.$meta, 'clear', {}) ?? 'Temizle',
			'save' => TranslationOverrides.string(_root.$meta, 'save', {}) ?? 'Kaydet',
			'cancel' => TranslationOverrides.string(_root.$meta, 'cancel', {}) ?? 'İptal',
			'myInformation' => TranslationOverrides.string(_root.$meta, 'myInformation', {}) ?? 'Bilgilerim',
			'myAddresses' => TranslationOverrides.string(_root.$meta, 'myAddresses', {}) ?? 'Adreslerim',
			'changePassword' => TranslationOverrides.string(_root.$meta, 'changePassword', {}) ?? 'Şifre Değiştir',
			'myOrders' => TranslationOverrides.string(_root.$meta, 'myOrders', {}) ?? 'Siparişlerim',
			'myReviews' => TranslationOverrides.string(_root.$meta, 'myReviews', {}) ?? 'Değerlendirmelerim',
			'logout' => TranslationOverrides.string(_root.$meta, 'logout', {}) ?? 'Çıkış Yap',
			'login' => TranslationOverrides.string(_root.$meta, 'login', {}) ?? 'Giriş Yap',
			'signup' => TranslationOverrides.string(_root.$meta, 'signup', {}) ?? 'Kayıt Ol',
			'country' => TranslationOverrides.string(_root.$meta, 'country', {}) ?? 'Ülke',
			'city' => TranslationOverrides.string(_root.$meta, 'city', {}) ?? 'Şehir',
			'address' => TranslationOverrides.string(_root.$meta, 'address', {}) ?? 'Adres',
			'postalCode' => TranslationOverrides.string(_root.$meta, 'postalCode', {}) ?? 'Posta Kodu',
			'phoneNumber' => TranslationOverrides.string(_root.$meta, 'phoneNumber', {}) ?? 'Telefon Numarası',
			'selectCountry' => TranslationOverrides.string(_root.$meta, 'selectCountry', {}) ?? 'Ülke Seçiniz',
			'appTitle' => TranslationOverrides.string(_root.$meta, 'appTitle', {}) ?? 'Mağaza Supabase',
			'noProducts' => TranslationOverrides.string(_root.$meta, 'noProducts', {}) ?? 'Ürün bulunamadı.',
			'sort' => TranslationOverrides.string(_root.$meta, 'sort', {}) ?? 'Sırala',
			'filter' => TranslationOverrides.string(_root.$meta, 'filter', {}) ?? 'Filtrele',
			'languageChanged' => TranslationOverrides.string(_root.$meta, 'languageChanged', {}) ?? 'Dil Türkçe olarak değiştirildi',
			'addressUpdated' => TranslationOverrides.string(_root.$meta, 'addressUpdated', {}) ?? 'Adres başarıyla güncellendi!',
			'adminDashboard' => TranslationOverrides.string(_root.$meta, 'adminDashboard', {}) ?? 'Yönetici Paneli',
			'users' => TranslationOverrides.string(_root.$meta, 'users', {}) ?? 'Kullanıcılar',
			'products' => TranslationOverrides.string(_root.$meta, 'products', {}) ?? 'Ürünler',
			'orders' => TranslationOverrides.string(_root.$meta, 'orders', {}) ?? 'Siparişler',
			'language' => TranslationOverrides.string(_root.$meta, 'language', {}) ?? 'Dil',
			'noCategories' => TranslationOverrides.string(_root.$meta, 'noCategories', {}) ?? 'Kategori bulunamadı.',
			'emptyCart' => TranslationOverrides.string(_root.$meta, 'emptyCart', {}) ?? 'Sepetiniz boş.',
			'total' => TranslationOverrides.string(_root.$meta, 'total', {}) ?? 'Toplam',
			'proceedToCheckout' => TranslationOverrides.string(_root.$meta, 'proceedToCheckout', {}) ?? 'Ödemeye Geç',
			'remove' => TranslationOverrides.string(_root.$meta, 'remove', {}) ?? 'Kaldır',
			'loginSignup' => TranslationOverrides.string(_root.$meta, 'loginSignup', {}) ?? 'Giriş Yap / Kayıt Ol',
			'noFavorites' => TranslationOverrides.string(_root.$meta, 'noFavorites', {}) ?? 'Henüz favori ürününüz yok.',
			'helpSupport' => TranslationOverrides.string(_root.$meta, 'helpSupport', {}) ?? 'Yardım & Destek',
			'searchProducts' => TranslationOverrides.string(_root.$meta, 'searchProducts', {}) ?? 'Ürün Ara',
			'noResultsFor' => TranslationOverrides.string(_root.$meta, 'noResultsFor', {}) ?? 'Sonuç bulunamadı:',
			'startTyping' => TranslationOverrides.string(_root.$meta, 'startTyping', {}) ?? 'Aramak için yazmaya başlayın...',
			'darkMode' => TranslationOverrides.string(_root.$meta, 'darkMode', {}) ?? 'Karanlık Mod',
			'addToCart' => TranslationOverrides.string(_root.$meta, 'addToCart', {}) ?? 'Sepete Ekle',
			'reviews' => TranslationOverrides.string(_root.$meta, 'reviews', {}) ?? 'Yorumlar',
			'writeReview' => TranslationOverrides.string(_root.$meta, 'writeReview', {}) ?? 'Yorum Yaz',
			'rating' => TranslationOverrides.string(_root.$meta, 'rating', {}) ?? 'Puan',
			'reviewTitle' => TranslationOverrides.string(_root.$meta, 'reviewTitle', {}) ?? 'Yorum Başlığı',
			'yourReview' => TranslationOverrides.string(_root.$meta, 'yourReview', {}) ?? 'Yorumunuz',
			'submitReview' => TranslationOverrides.string(_root.$meta, 'submitReview', {}) ?? 'Yorumu Gönder',
			'username' => TranslationOverrides.string(_root.$meta, 'username', {}) ?? 'Kullanıcı Adı',
			'email' => TranslationOverrides.string(_root.$meta, 'email', {}) ?? 'E-posta',
			'dateOfBirth' => TranslationOverrides.string(_root.$meta, 'dateOfBirth', {}) ?? 'Doğum Tarihi',
			'selectGender' => TranslationOverrides.string(_root.$meta, 'selectGender', {}) ?? 'Cinsiyet Seçin',
			'savePersonalInfo' => TranslationOverrides.string(_root.$meta, 'savePersonalInfo', {}) ?? 'Kişisel Bilgileri Kaydet',
			'profileUpdated' => TranslationOverrides.string(_root.$meta, 'profileUpdated', {}) ?? 'Profil başarıyla güncellendi!',
			'saveAddress' => TranslationOverrides.string(_root.$meta, 'saveAddress', {}) ?? 'Adresi Kaydet',
			'newPassword' => TranslationOverrides.string(_root.$meta, 'newPassword', {}) ?? 'Yeni Şifre',
			'confirmNewPassword' => TranslationOverrides.string(_root.$meta, 'confirmNewPassword', {}) ?? 'Yeni Şifreyi Onayla',
			'updatePassword' => TranslationOverrides.string(_root.$meta, 'updatePassword', {}) ?? 'Şifreyi Güncelle',
			'passwordChanged' => TranslationOverrides.string(_root.$meta, 'passwordChanged', {}) ?? 'Şifre başarıyla değiştirildi!',
			'productAddedToCart' => TranslationOverrides.string(_root.$meta, 'productAddedToCart', {}) ?? 'Ürün sepete eklendi!',
			'failedToAddCart' => TranslationOverrides.string(_root.$meta, 'failedToAddCart', {}) ?? 'Ürün eklenemedi. Lütfen giriş yapıp tekrar deneyin.',
			'reviewSubmitted' => TranslationOverrides.string(_root.$meta, 'reviewSubmitted', {}) ?? 'Yorum gönderildi!',
			'failedSubmitReview' => TranslationOverrides.string(_root.$meta, 'failedSubmitReview', {}) ?? 'Yorum gönderilemedi. Giriş yaptığınızdan ve yorumun boş olmadığından emin olun.',
			'account' => TranslationOverrides.string(_root.$meta, 'account', {}) ?? 'Hesap',
			'shopping' => TranslationOverrides.string(_root.$meta, 'shopping', {}) ?? 'Alışveriş',
			'general' => TranslationOverrides.string(_root.$meta, 'general', {}) ?? 'Genel',
			'admin' => TranslationOverrides.string(_root.$meta, 'admin', {}) ?? 'Yönetici',
			'coupons' => TranslationOverrides.string(_root.$meta, 'coupons', {}) ?? 'Kuponlar',
			'welcomeTitle' => TranslationOverrides.string(_root.$meta, 'welcomeTitle', {}) ?? 'Mağazaya Hoşgeldiniz',
			'welcomeSubtitle' => TranslationOverrides.string(_root.$meta, 'welcomeSubtitle', {}) ?? 'Devam etmek için giriş yapın veya hesap oluşturun',
			'dontHaveAccount' => TranslationOverrides.string(_root.$meta, 'dontHaveAccount', {}) ?? 'Hesabınız yok mu? Kayıt Ol',
			'alreadyHaveAccount' => TranslationOverrides.string(_root.$meta, 'alreadyHaveAccount', {}) ?? 'Zaten hesabınız var mı? Giriş Yap',
			'signIn' => TranslationOverrides.string(_root.$meta, 'signIn', {}) ?? 'Giriş Yap',
			'totalRevenue' => TranslationOverrides.string(_root.$meta, 'totalRevenue', {}) ?? 'Toplam Gelir',
			'totalOrders' => TranslationOverrides.string(_root.$meta, 'totalOrders', {}) ?? 'Toplam Sipariş',
			'totalUsers' => TranslationOverrides.string(_root.$meta, 'totalUsers', {}) ?? 'Toplam Kullanıcı',
			'totalProducts' => TranslationOverrides.string(_root.$meta, 'totalProducts', {}) ?? 'Toplam Ürün',
			'recentOrders' => TranslationOverrides.string(_root.$meta, 'recentOrders', {}) ?? 'Son Siparişler',
			'noRecentOrders' => TranslationOverrides.string(_root.$meta, 'noRecentOrders', {}) ?? 'Son sipariş yok.',
			'orderNumber' => TranslationOverrides.string(_root.$meta, 'orderNumber', {}) ?? 'Sipariş #',
			'guest' => TranslationOverrides.string(_root.$meta, 'guest', {}) ?? 'Misafir',
			'newUsers' => TranslationOverrides.string(_root.$meta, 'newUsers', {}) ?? 'Yeni Kullanıcılar',
			'noNewUsers' => TranslationOverrides.string(_root.$meta, 'noNewUsers', {}) ?? 'Yeni kullanıcı yok.',
			'unnamed' => TranslationOverrides.string(_root.$meta, 'unnamed', {}) ?? 'İsimsiz',
			'unnamedUser' => TranslationOverrides.string(_root.$meta, 'unnamedUser', {}) ?? 'İsimsiz Kullanıcı',
			'joined' => TranslationOverrides.string(_root.$meta, 'joined', {}) ?? 'Katıldı',
			'dailyRevenue' => TranslationOverrides.string(_root.$meta, 'dailyRevenue', {}) ?? 'Günlük gelir',
			'last7DaysRevenueOrders' => TranslationOverrides.string(_root.$meta, 'last7DaysRevenueOrders', {}) ?? 'Son 7 Gün - Gelir & Siparişler',
			'orderStatuses' => TranslationOverrides.string(_root.$meta, 'orderStatuses', {}) ?? 'Sipariş Durumları',
			'last7DaysNewUsers' => TranslationOverrides.string(_root.$meta, 'last7DaysNewUsers', {}) ?? 'Son 7 Gün - Yeni Kullanıcılar',
			'dailyNewUsers' => TranslationOverrides.string(_root.$meta, 'dailyNewUsers', {}) ?? 'Günlük yeni kullanıcı',
			'last7DaysNewProducts' => TranslationOverrides.string(_root.$meta, 'last7DaysNewProducts', {}) ?? 'Son 7 Gün - Yeni Ürünler',
			'dailyNewProducts' => TranslationOverrides.string(_root.$meta, 'dailyNewProducts', {}) ?? 'Günlük yeni ürün',
			'ordersShort' => TranslationOverrides.string(_root.$meta, 'ordersShort', {}) ?? 'sip.',
			'dayAbbr' => TranslationOverrides.string(_root.$meta, 'dayAbbr', {}) ?? 'Gün',
			'unexpectedError' => TranslationOverrides.string(_root.$meta, 'unexpectedError', {}) ?? 'Beklenmeyen bir hata oluştu.',
			'errorPrefix' => TranslationOverrides.string(_root.$meta, 'errorPrefix', {}) ?? 'Hata: ',
			'noUsersFound' => TranslationOverrides.string(_root.$meta, 'noUsersFound', {}) ?? 'Kullanıcı bulunamadı.',
			'noEmail' => TranslationOverrides.string(_root.$meta, 'noEmail', {}) ?? 'E-posta yok',
			'rolePrefix' => TranslationOverrides.string(_root.$meta, 'rolePrefix', {}) ?? 'Rol: ',
			'searchProductsHint' => TranslationOverrides.string(_root.$meta, 'searchProductsHint', {}) ?? 'Ürün ara...',
			'sortByDate' => TranslationOverrides.string(_root.$meta, 'sortByDate', {}) ?? 'Tarihe Göre Sırala',
			'sortByPopularity' => TranslationOverrides.string(_root.$meta, 'sortByPopularity', {}) ?? 'Popülerliğe Göre Sırala',
			'sortByPrice' => TranslationOverrides.string(_root.$meta, 'sortByPrice', {}) ?? 'Fiyata Göre Sırala',
			'filters' => TranslationOverrides.string(_root.$meta, 'filters', {}) ?? 'Filtreler',
			'mainCategory' => TranslationOverrides.string(_root.$meta, 'mainCategory', {}) ?? 'Ana Kategori',
			'subCategory' => TranslationOverrides.string(_root.$meta, 'subCategory', {}) ?? 'Alt Kategori',
			'specificCategory' => TranslationOverrides.string(_root.$meta, 'specificCategory', {}) ?? 'Özel Kategori',
			'shoeSizes' => TranslationOverrides.string(_root.$meta, 'shoeSizes', {}) ?? 'Ayakkabı Numaraları',
			'sizeAgeGroups' => TranslationOverrides.string(_root.$meta, 'sizeAgeGroups', {}) ?? 'Beden / Yaş Grupları',
			'brands' => TranslationOverrides.string(_root.$meta, 'brands', {}) ?? 'Markalar',
			'addNewProduct' => TranslationOverrides.string(_root.$meta, 'addNewProduct', {}) ?? 'Yeni Ürün Ekle',
			'editProduct' => TranslationOverrides.string(_root.$meta, 'editProduct', {}) ?? 'Ürünü Düzenle',
			'retry' => TranslationOverrides.string(_root.$meta, 'retry', {}) ?? 'Tekrar Dene',
			'savingChanges' => TranslationOverrides.string(_root.$meta, 'savingChanges', {}) ?? 'Değişiklikler Kaydediliyor...',
			'addingProduct' => TranslationOverrides.string(_root.$meta, 'addingProduct', {}) ?? 'Ürün Ekleniyor...',
			'productUpdatedSuccess' => TranslationOverrides.string(_root.$meta, 'productUpdatedSuccess', {}) ?? 'Ürün Başarıyla Güncellendi!',
			'productAddedSuccess' => TranslationOverrides.string(_root.$meta, 'productAddedSuccess', {}) ?? 'Ürün Başarıyla Eklendi!',
			'addAnotherProduct' => TranslationOverrides.string(_root.$meta, 'addAnotherProduct', {}) ?? 'Başka Ürün Ekle',
			'goToProducts' => TranslationOverrides.string(_root.$meta, 'goToProducts', {}) ?? 'Ürünlere Git',
			'productName' => TranslationOverrides.string(_root.$meta, 'productName', {}) ?? 'Ürün Adı',
			'description' => TranslationOverrides.string(_root.$meta, 'description', {}) ?? 'Açıklama',
			'price' => TranslationOverrides.string(_root.$meta, 'price', {}) ?? 'Fiyat',
			'sku' => TranslationOverrides.string(_root.$meta, 'sku', {}) ?? 'SKU (Stok Kodu)',
			'stockQuantity' => TranslationOverrides.string(_root.$meta, 'stockQuantity', {}) ?? 'Stok Miktarı',
			'selectShoeSizes' => TranslationOverrides.string(_root.$meta, 'selectShoeSizes', {}) ?? 'Ayakkabı Numarası Seçin',
			'selectSizeAgeGroups' => TranslationOverrides.string(_root.$meta, 'selectSizeAgeGroups', {}) ?? 'Beden / Yaş Grubu Seçin',
			'brand' => TranslationOverrides.string(_root.$meta, 'brand', {}) ?? 'Marka',
			'saveChanges' => TranslationOverrides.string(_root.$meta, 'saveChanges', {}) ?? 'Değişiklikleri Kaydet',
			'addProduct' => TranslationOverrides.string(_root.$meta, 'addProduct', {}) ?? 'Ürün Ekle',
			'pleaseSelectA' => TranslationOverrides.string(_root.$meta, 'pleaseSelectA', {}) ?? 'Lütfen seçiniz: ',
			'pickImage' => TranslationOverrides.string(_root.$meta, 'pickImage', {}) ?? 'Resim Seç',
			'pleaseEnterA' => TranslationOverrides.string(_root.$meta, 'pleaseEnterA', {}) ?? 'Lütfen giriniz: ',
			'addNewBrandTitle' => TranslationOverrides.string(_root.$meta, 'addNewBrandTitle', {}) ?? 'Yeni Marka Ekle',
			'enterBrandName' => TranslationOverrides.string(_root.$meta, 'enterBrandName', {}) ?? 'Marka adı giriniz',
			'errorSelectCategoryBrand' => TranslationOverrides.string(_root.$meta, 'errorSelectCategoryBrand', {}) ?? 'Lütfen bir kategori ve marka seçin.',
			'errorSelectImage' => TranslationOverrides.string(_root.$meta, 'errorSelectImage', {}) ?? 'Lütfen bir resim seçin.',
			'errorStorageBucketMissing' => TranslationOverrides.string(_root.$meta, 'errorStorageBucketMissing', {}) ?? 'Ürün kaydedilemedi: Depolama alanı \'products\' bulunamadı. Lütfen Supabase projenizde oluşturun.',
			'errorStorage' => TranslationOverrides.string(_root.$meta, 'errorStorage', {}) ?? 'Ürün kaydedilemedi: Depolama hatası: ',
			'errorSaveProduct' => TranslationOverrides.string(_root.$meta, 'errorSaveProduct', {}) ?? 'Ürün kaydedilemedi: ',
			'noOrdersFound' => TranslationOverrides.string(_root.$meta, 'noOrdersFound', {}) ?? 'Sipariş bulunamadı.',
			'userPrefix' => TranslationOverrides.string(_root.$meta, 'userPrefix', {}) ?? 'Kullanıcı: ',
			'totalPrefix' => TranslationOverrides.string(_root.$meta, 'totalPrefix', {}) ?? 'Toplam: \$',
			'adminSettings' => TranslationOverrides.string(_root.$meta, 'adminSettings', {}) ?? 'Yönetici Ayarları',
			'adminInformation' => TranslationOverrides.string(_root.$meta, 'adminInformation', {}) ?? 'Yönetici Bilgileri',
			'emailLabel' => TranslationOverrides.string(_root.$meta, 'emailLabel', {}) ?? 'E-posta:',
			'fullNameLabel' => TranslationOverrides.string(_root.$meta, 'fullNameLabel', {}) ?? 'Tam Ad:',
			'roleLabel' => TranslationOverrides.string(_root.$meta, 'roleLabel', {}) ?? 'Rol:',
			'memberSinceLabel' => TranslationOverrides.string(_root.$meta, 'memberSinceLabel', {}) ?? 'Üyelik Tarihi:',
			'adminNotLoggedIn' => TranslationOverrides.string(_root.$meta, 'adminNotLoggedIn', {}) ?? 'Yönetici girişi yapılmamış.',
			'errorLoadAdminInfo' => TranslationOverrides.string(_root.$meta, 'errorLoadAdminInfo', {}) ?? 'Yönetici bilgileri yüklenemedi: ',
			'somethingWentWrong' => TranslationOverrides.string(_root.$meta, 'somethingWentWrong', {}) ?? 'Bir şeyler ters gitti.',
			'noProductsForSelection' => TranslationOverrides.string(_root.$meta, 'noProductsForSelection', {}) ?? 'Bu seçim için ürün bulunamadı.',
			'productDetail' => TranslationOverrides.string(_root.$meta, 'productDetail', {}) ?? 'Ürün Detayı',
			'reviewsCount' => TranslationOverrides.string(_root.$meta, 'reviewsCount', {}) ?? 'Yorumlar ({count})',
			'noReviewsYet' => TranslationOverrides.string(_root.$meta, 'noReviewsYet', {}) ?? 'Henüz yorum yok.',
			'emailCannotBeChanged' => TranslationOverrides.string(_root.$meta, 'emailCannotBeChanged', {}) ?? '* E-posta adresi buradan doğrudan değiştirilemez.',
			'genderMale' => TranslationOverrides.string(_root.$meta, 'genderMale', {}) ?? 'Erkek',
			'genderFemale' => TranslationOverrides.string(_root.$meta, 'genderFemale', {}) ?? 'Kadın',
			'genderOther' => TranslationOverrides.string(_root.$meta, 'genderOther', {}) ?? 'Diğer',
			'genderPreferNotToSay' => TranslationOverrides.string(_root.$meta, 'genderPreferNotToSay', {}) ?? 'Belirtmek istemiyorum',
			'loginToViewInfo' => TranslationOverrides.string(_root.$meta, 'loginToViewInfo', {}) ?? 'Bilgileri görmek için lütfen giriş yapın.',
			'selectCountryFirst' => TranslationOverrides.string(_root.$meta, 'selectCountryFirst', {}) ?? 'Önce Ülke Seçin',
			'selectCity' => TranslationOverrides.string(_root.$meta, 'selectCity', {}) ?? 'Şehir Seçin',
			'loginToManageAddresses' => TranslationOverrides.string(_root.$meta, 'loginToManageAddresses', {}) ?? 'Adresleri yönetmek için lütfen giriş yapın.',
			'loginToViewFavorites' => TranslationOverrides.string(_root.$meta, 'loginToViewFavorites', {}) ?? 'Favorilerinizi görmek için lütfen giriş yapın.',
			'selectPrefix' => TranslationOverrides.string(_root.$meta, 'selectPrefix', {}) ?? 'Seçiniz: ',
			'failedChangePassword' => TranslationOverrides.string(_root.$meta, 'failedChangePassword', {}) ?? 'Şifre değiştirilemedi. Lütfen girişlerinizi kontrol edin.',
			'onboarding' => TranslationOverrides.string(_root.$meta, 'onboarding', {}) ?? 'Karşılama',
			'onboardingScreen' => TranslationOverrides.string(_root.$meta, 'onboardingScreen', {}) ?? 'Karşılama Ekranı',
			'goToHome' => TranslationOverrides.string(_root.$meta, 'goToHome', {}) ?? 'Ana Sayfaya Git',
			'password' => TranslationOverrides.string(_root.$meta, 'password', {}) ?? 'Şifre',
			'confirmPassword' => TranslationOverrides.string(_root.$meta, 'confirmPassword', {}) ?? 'Şifreyi Onayla',
			'logoutSuccess' => TranslationOverrides.string(_root.$meta, 'logoutSuccess', {}) ?? 'Başarıyla çıkış yapıldı!',
			'addedToFavorites' => TranslationOverrides.string(_root.$meta, 'addedToFavorites', {}) ?? 'Favorilere eklendi!',
			'removedFromFavorites' => TranslationOverrides.string(_root.$meta, 'removedFromFavorites', {}) ?? 'Favorilerden çıkarıldı.',
			'wishlistUpdateFailed' => TranslationOverrides.string(_root.$meta, 'wishlistUpdateFailed', {}) ?? 'İstek listesi güncellenemedi. Lütfen tekrar deneyin.',
			'filterAll' => TranslationOverrides.string(_root.$meta, 'filterAll', {}) ?? 'Tümü',
			'filterVerified' => TranslationOverrides.string(_root.$meta, 'filterVerified', {}) ?? 'Doğrulanmış Satın Alma',
			'filterProductRating' => TranslationOverrides.string(_root.$meta, 'filterProductRating', {}) ?? 'Ürün Puanı',
			'filterDeliveryRating' => TranslationOverrides.string(_root.$meta, 'filterDeliveryRating', {}) ?? 'Teslimat Puanı',
			'filterWithComment' => TranslationOverrides.string(_root.$meta, 'filterWithComment', {}) ?? 'Yorumlu',
			'haveACoupon' => TranslationOverrides.string(_root.$meta, 'haveACoupon', {}) ?? 'Kuponunuz var mı?',
			'enterCouponCode' => TranslationOverrides.string(_root.$meta, 'enterCouponCode', {}) ?? 'Kupon kodunu girin',
			'applyCoupon' => TranslationOverrides.string(_root.$meta, 'applyCoupon', {}) ?? 'Uygula',
			'removeCoupon' => TranslationOverrides.string(_root.$meta, 'removeCoupon', {}) ?? 'Kuponu Kaldır',
			'discount' => TranslationOverrides.string(_root.$meta, 'discount', {}) ?? 'İndirim',
			'couponRemoved' => TranslationOverrides.string(_root.$meta, 'couponRemoved', {}) ?? 'Kupon kaldırıldı.',
			'couponAppliedSuccessfully' => TranslationOverrides.string(_root.$meta, 'couponAppliedSuccessfully', {}) ?? 'Kupon başarıyla uygulandı!',
			'invalidCouponCode' => TranslationOverrides.string(_root.$meta, 'invalidCouponCode', {}) ?? 'Geçersiz kupon kodu.',
			'couponNotActive' => TranslationOverrides.string(_root.$meta, 'couponNotActive', {}) ?? 'Kupon aktif değil.',
			'couponExpired' => TranslationOverrides.string(_root.$meta, 'couponExpired', {}) ?? 'Kuponun süresi doldu.',
			'couponLimitReached' => TranslationOverrides.string(_root.$meta, 'couponLimitReached', {}) ?? 'Kupon kullanım sınırı aşıldı.',
			'minimumPurchaseRequired' => TranslationOverrides.string(_root.$meta, 'minimumPurchaseRequired', {}) ?? 'Minimum {amount} tutarında alışveriş gerekli.',
			'confirmLogoutMessage' => TranslationOverrides.string(_root.$meta, 'confirmLogoutMessage', {}) ?? 'Çıkış yapmak istediğinizden emin misiniz?',
			'welcomeBackLogin' => TranslationOverrides.string(_root.$meta, 'welcomeBackLogin', {}) ?? 'Tekrar hoş geldiniz! Giriş başarılı.',
			'seeAll' => TranslationOverrides.string(_root.$meta, 'seeAll', {}) ?? 'Tümünü gör',
			'recommendedForYou' => TranslationOverrides.string(_root.$meta, 'recommendedForYou', {}) ?? 'Sizin için önerilenler',
			'shopByBrand' => TranslationOverrides.string(_root.$meta, 'shopByBrand', {}) ?? 'Markaya göre alışveriş',
			'collections' => TranslationOverrides.string(_root.$meta, 'collections', {}) ?? 'Koleksiyonlar',
			'collection' => TranslationOverrides.string(_root.$meta, 'collection', {}) ?? 'Koleksiyon',
			'addedToFavoritesCategory' => TranslationOverrides.string(_root.$meta, 'addedToFavoritesCategory', {}) ?? 'Favorilere eklendi',
			'removedFromFavoritesCategory' => TranslationOverrides.string(_root.$meta, 'removedFromFavoritesCategory', {}) ?? 'Favorilerden çıkarıldı',
			'undo' => TranslationOverrides.string(_root.$meta, 'undo', {}) ?? 'Geri al',
			'loginToViewCart' => TranslationOverrides.string(_root.$meta, 'loginToViewCart', {}) ?? 'Sepetinizi görmek için giriş yapın.',
			'loginToAddToCart' => TranslationOverrides.string(_root.$meta, 'loginToAddToCart', {}) ?? 'Sepete ürün eklemek için giriş yapın.',
			'loginToAddToFavorites' => TranslationOverrides.string(_root.$meta, 'loginToAddToFavorites', {}) ?? 'Favorilere eklemek için giriş yapmalısınız.',
			'categoryAddedToFavorites' => TranslationOverrides.string(_root.$meta, 'categoryAddedToFavorites', {}) ?? '{name} favorilerinize eklendi',
			'categoryRemovedFromFavorites' => TranslationOverrides.string(_root.$meta, 'categoryRemovedFromFavorites', {}) ?? '{name} favorilerinizden çıkarıldı',
			'removedFromCart' => TranslationOverrides.string(_root.$meta, 'removedFromCart', {}) ?? 'Sepetten çıkarıldı',
			'brandAddedToFavorites' => TranslationOverrides.string(_root.$meta, 'brandAddedToFavorites', {}) ?? 'Marka favorilere eklendi',
			'brandRemovedFromFavorites' => TranslationOverrides.string(_root.$meta, 'brandRemovedFromFavorites', {}) ?? 'Marka favorilerden çıkarıldı',
			'endsIn' => TranslationOverrides.string(_root.$meta, 'endsIn', {}) ?? 'Bitiş',
			'specialOffer' => TranslationOverrides.string(_root.$meta, 'specialOffer', {}) ?? 'Özel Teklif',
			'limitedTimeOffer' => TranslationOverrides.string(_root.$meta, 'limitedTimeOffer', {}) ?? 'Sınırlı süre teklifi',
			'dealsOfTheDay' => TranslationOverrides.string(_root.$meta, 'dealsOfTheDay', {}) ?? 'Günün Fırsatları',
			'flashSale' => TranslationOverrides.string(_root.$meta, 'flashSale', {}) ?? 'Flaş İndirim',
			'checkoutTitle' => TranslationOverrides.string(_root.$meta, 'checkoutTitle', {}) ?? 'Ödeme',
			'stepAddress' => TranslationOverrides.string(_root.$meta, 'stepAddress', {}) ?? 'Adres',
			'stepShipping' => TranslationOverrides.string(_root.$meta, 'stepShipping', {}) ?? 'Kargo',
			'stepPayment' => TranslationOverrides.string(_root.$meta, 'stepPayment', {}) ?? 'Ödeme',
			'stepSummary' => TranslationOverrides.string(_root.$meta, 'stepSummary', {}) ?? 'Özet',
			'continueButton' => TranslationOverrides.string(_root.$meta, 'continueButton', {}) ?? 'Devam',
			'backButton' => TranslationOverrides.string(_root.$meta, 'backButton', {}) ?? 'Geri',
			'placeOrder' => TranslationOverrides.string(_root.$meta, 'placeOrder', {}) ?? 'Siparişi Ver',
			'orderPlacedTitle' => TranslationOverrides.string(_root.$meta, 'orderPlacedTitle', {}) ?? 'Sipariş Alındı!',
			'orderPlacedDescription' => TranslationOverrides.string(_root.$meta, 'orderPlacedDescription', {}) ?? 'Siparişiniz alındı.',
			'backToHome' => TranslationOverrides.string(_root.$meta, 'backToHome', {}) ?? 'Ana Sayfaya Dön',
			'fillRequiredFields' => TranslationOverrides.string(_root.$meta, 'fillRequiredFields', {}) ?? 'Lütfen zorunlu alanları doldurun.',
			'selectShippingMethod' => TranslationOverrides.string(_root.$meta, 'selectShippingMethod', {}) ?? 'Lütfen kargo yöntemi seçin.',
			'selectPaymentMethod' => TranslationOverrides.string(_root.$meta, 'selectPaymentMethod', {}) ?? 'Lütfen ödeme yöntemi seçin.',
			'firstName' => TranslationOverrides.string(_root.$meta, 'firstName', {}) ?? 'Ad',
			'lastName' => TranslationOverrides.string(_root.$meta, 'lastName', {}) ?? 'Soyad',
			'addressLine1' => TranslationOverrides.string(_root.$meta, 'addressLine1', {}) ?? 'Adres',
			'sameAsBilling' => TranslationOverrides.string(_root.$meta, 'sameAsBilling', {}) ?? 'Fatura adresi ile aynı',
			'deleteAccount' => TranslationOverrides.string(_root.$meta, 'deleteAccount', {}) ?? 'Hesabı Sil',
			'deleteAccountTitle' => TranslationOverrides.string(_root.$meta, 'deleteAccountTitle', {}) ?? 'Hesabı Sil?',
			'deleteAccountMessage30Days' => TranslationOverrides.string(_root.$meta, 'deleteAccountMessage30Days', {}) ?? 'Hesabınız silinmek üzere planlanacaktır. 30 gün içinde kalıcı olarak silinecektir. Bu süre içinde tekrar giriş yaparak iptal edebilirsiniz.',
			'deleteAccountWhatWillBeDeleted' => TranslationOverrides.string(_root.$meta, 'deleteAccountWhatWillBeDeleted', {}) ?? 'Kalıcı olarak silinecekler:',
			'deleteAccountItemProfile' => TranslationOverrides.string(_root.$meta, 'deleteAccountItemProfile', {}) ?? 'Profiliniz ve kişisel bilgileriniz',
			'deleteAccountItemOrders' => TranslationOverrides.string(_root.$meta, 'deleteAccountItemOrders', {}) ?? 'Tüm siparişleriniz ve sipariş geçmişiniz',
			'deleteAccountItemAddresses' => TranslationOverrides.string(_root.$meta, 'deleteAccountItemAddresses', {}) ?? 'Kayıtlı adresleriniz',
			'deleteAccountItemReviews' => TranslationOverrides.string(_root.$meta, 'deleteAccountItemReviews', {}) ?? 'Tüm yorumlarınız ve puanlarınız',
			'deleteAccountCannotUndo' => TranslationOverrides.string(_root.$meta, 'deleteAccountCannotUndo', {}) ?? '30 gün sonra bu işlem geri alınamaz. 30 gün içinde giriş yaparak iptal edebilirsiniz.',
			'deleteAccountContinue' => TranslationOverrides.string(_root.$meta, 'deleteAccountContinue', {}) ?? 'Devam',
			'deleteAccountGoBack' => TranslationOverrides.string(_root.$meta, 'deleteAccountGoBack', {}) ?? 'Geri',
			'deleteAccountFinalConfirm' => TranslationOverrides.string(_root.$meta, 'deleteAccountFinalConfirm', {}) ?? 'Son Onay',
			'deleteAccountSure' => TranslationOverrides.string(_root.$meta, 'deleteAccountSure', {}) ?? 'Hesap silme işlemini planlamak istediğinize emin misiniz?',
			'deleteAccountEmailLabel' => TranslationOverrides.string(_root.$meta, 'deleteAccountEmailLabel', {}) ?? 'Hesap: {email}',
			'deleteAccountUnderstandPermanent' => TranslationOverrides.string(_root.$meta, 'deleteAccountUnderstandPermanent', {}) ?? 'Hesabımın 30 gün içinde silineceğini ve bu süre içinde giriş yaparak iptal edebileceğimi anlıyorum',
			'deleteMyAccount' => TranslationOverrides.string(_root.$meta, 'deleteMyAccount', {}) ?? 'Hesabımı Sil',
			'deleteAccountSuccess' => TranslationOverrides.string(_root.$meta, 'deleteAccountSuccess', {}) ?? 'Hesap silme planlandı. Hesabınız 30 gün içinde kaldırılacaktır. İptal etmek için bu süre içinde giriş yapabilirsiniz.',
			'deleteAccountFailed' => TranslationOverrides.string(_root.$meta, 'deleteAccountFailed', {}) ?? 'Hesap silme planlanamadı. Lütfen tekrar deneyin veya destek ile iletişime geçin.',
			'selectAddress' => TranslationOverrides.string(_root.$meta, 'selectAddress', {}) ?? 'Adres Seçin',
			'addNewAddress' => TranslationOverrides.string(_root.$meta, 'addNewAddress', {}) ?? 'Yeni Adres Ekle',
			'billingAddress' => TranslationOverrides.string(_root.$meta, 'billingAddress', {}) ?? 'Fatura Adresi',
			'newAddress' => TranslationOverrides.string(_root.$meta, 'newAddress', {}) ?? 'Yeni Adres',
			'defaultAddress' => TranslationOverrides.string(_root.$meta, 'defaultAddress', {}) ?? 'Varsayılan',
			'addressAdded' => TranslationOverrides.string(_root.$meta, 'addressAdded', {}) ?? 'Adres başarıyla eklendi!',
			'addressDeleted' => TranslationOverrides.string(_root.$meta, 'addressDeleted', {}) ?? 'Adres başarıyla silindi!',
			'defaultAddressSet' => TranslationOverrides.string(_root.$meta, 'defaultAddressSet', {}) ?? 'Varsayılan adres başarıyla ayarlandı!',
			'addressLabelHint' => TranslationOverrides.string(_root.$meta, 'addressLabelHint', {}) ?? 'örn. Ev, Ofis',
			'confirmDeleteAddress' => TranslationOverrides.string(_root.$meta, 'confirmDeleteAddress', {}) ?? 'Bu adresi silmek istediğinize emin misiniz?',
			'optional' => TranslationOverrides.string(_root.$meta, 'optional', {}) ?? 'İsteğe bağlı',
			'setAsDefault' => TranslationOverrides.string(_root.$meta, 'setAsDefault', {}) ?? 'Varsayılan Yap',
			'editAddress' => TranslationOverrides.string(_root.$meta, 'editAddress', {}) ?? 'Adresi Düzenle',
			'addAddress' => TranslationOverrides.string(_root.$meta, 'addAddress', {}) ?? 'Adres Ekle',
			'errorOccurred' => TranslationOverrides.string(_root.$meta, 'errorOccurred', {}) ?? 'Bir hata oluştu. Lütfen tekrar deneyin.',
			'delete' => TranslationOverrides.string(_root.$meta, 'delete', {}) ?? 'Sil',
			'currency' => TranslationOverrides.string(_root.$meta, 'currency', {}) ?? 'Currency',
			'quickAccess' => TranslationOverrides.string(_root.$meta, 'quickAccess', {}) ?? 'Quick access',
			'productReviews' => TranslationOverrides.string(_root.$meta, 'productReviews', {}) ?? 'Product reviews',
			'userAddresses' => TranslationOverrides.string(_root.$meta, 'userAddresses', {}) ?? 'User addresses',
			'addresses' => TranslationOverrides.string(_root.$meta, 'addresses', {}) ?? 'Addresses',
			'options' => TranslationOverrides.string(_root.$meta, 'options', {}) ?? 'Options',
			'details' => TranslationOverrides.string(_root.$meta, 'details', {}) ?? 'Details',
			'active' => TranslationOverrides.string(_root.$meta, 'active', {}) ?? 'Active',
			'inactive' => TranslationOverrides.string(_root.$meta, 'inactive', {}) ?? 'Inactive',
			'pending' => TranslationOverrides.string(_root.$meta, 'pending', {}) ?? 'Pending',
			'approved' => TranslationOverrides.string(_root.$meta, 'approved', {}) ?? 'Approved',
			'rejected' => TranslationOverrides.string(_root.$meta, 'rejected', {}) ?? 'Rejected',
			'shoppingCart' => TranslationOverrides.string(_root.$meta, 'shoppingCart', {}) ?? 'Shopping Cart',
			'subtotal' => TranslationOverrides.string(_root.$meta, 'subtotal', {}) ?? 'Subtotal',
			'viewAppConfigJson' => TranslationOverrides.string(_root.$meta, 'viewAppConfigJson', {}) ?? 'View app_config.json',
			'revenueAndOrdersByPeriod' => TranslationOverrides.string(_root.$meta, 'revenueAndOrdersByPeriod', {}) ?? 'Revenue & orders by period',
			_ => null,
		};
	}
}
