# Package Info
name: core
description: "A new Flutter package project."
version: 0.0.1

# Environment Constraints
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

# Main Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0      # State management
  injectable: ^2.5.0        # Dependency injection
  logger: ^2.5.0            # Logging utility

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.13           # Code generation
  injectable_generator: 2.6.2    # Injectable code generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# (Add Flutter-specific configuration here if needed)
