# Package Info
name: core
description: "Core utilities, base classes, and shared logic for the OSMEA Flutter project."
version: 0.0.1

# Environment Constraints
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

# -------------------------------
# Regular dependencies
# -------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0      # State management
  go_router: ^15.1.1
  injectable: ^2.5.0        # Dependency injection
  logger: ^2.5.0            # Logging utility
  slang: ^4.7.1
  flutter_localizations: # add this
    sdk: flutter
  intl: any
  slang_flutter: ^4.7.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  flutter_lints: ^5.0.0
  

# -------------------------------
# Development dependencies
# -------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.13           # Code generation
  injectable_generator: 2.6.2    # Injectable code generator
  slang_build_runner: ^4.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# (Add Flutter-specific configuration here if needed)
