name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

# Environment configuration
environment:
  sdk: ^3.6.1

# -------------------------------
# Regular dependencies
# -------------------------------
dependencies:
  # Flutter SDK dependency
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.8

  # Local core package
  core:
    path: ../../core

  # State management
  flutter_bloc: ^9.1.0

  # Dependency injection
  injectable: ^2.5.0
  get_it: ^8.0.3
  go_router: ^15.1.1

# -------------------------------
# Development dependencies
# -------------------------------
dev_dependencies:
  # Flutter testing framework
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^5.0.0

  # Code generation tools
  build_runner: 2.4.13
  injectable_generator: 2.6.2

# Flutter-specific configuration
flutter:
  uses-material-design: true
