name: example
description: "Example app demonstrating the Shopify API integration with the osmea apis package."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # API Package
  apis:
    path: ../../apis
  
  # Dependency Injection
  injectable: 2.5.0
  get_it: 7.7.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
    
  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: 2.4.13
  injectable_generator: 2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/config.json































